### ISSUE TITLE
Feature request: SponsorBlock

### ISSUE THREAD

**Issue by Gianni-Ingurgio** [SwapnilSoni1999/spotify-dl#103]
It would be nice to be able to use the [AponsorBlock API or database](https://sponsor.ajay.app/) to skip non-music segments and avoid having to manually trim music videos. For reference, I also found [SponSkrub](https://github.com/faissaloo/SponSkrub),  which could be useful.

**Comment by phyzical** [comment]
hmm interesting, there is also https://www.npmjs.com/package/sponsorblock-api.

Looks like sponscrub is fully cli and not nodeable

i would be interested at implementing this the only thing thats making me a bit hesitant is it looks like there is only 1.5 million reported videos so id wager a guess the odds of the found video being one of these to be fairly low id assume youtube has billions

But ill still have a crack and a few totally random videos and see what it returns and go from there

**Comment by phyzical** [comment]
Well i tried a few random videos ranging in view counts and they all seemed to reflect the sponsor blocks, so i think this will be worth it

**Comment by phyzical** [comment]
This should now be support by pr https://github.com/SwapnilSoni1999/spotify-dl/pull/102 

@Gianni-Ingurgio feel free to give it a try and let me know if it works as you would expect 👍
