### ISSUE TITLE
Could you make Instructions on how to use the option flags.

### ISSUE THREAD

**Issue by theofficialgrand1** [SwapnilSoni1999/spotify-dl#107]
Whenever I use the option flags the command line will come back with 
See spotifydl --help for instructions
I don't know wether my flags have been done or not. I don't know how to type the flags. For my username and password do I put them in Quotes or what? For saving the outputOnly it doesn't work.

**Comment by phyzical** [comment]
Could you please use the issue template next time as if you did we would have all the information to understand what exactly you are doing?

whats the exact command you are running?

 what are you expecting to happen that isn't happening?
 
 if i try to use the output only flag it is set to true

```
% spotifydl "test" --oo
sdads true
⠋ Searching… Please be patient :)
⠼ Searching… Please be patient :)
Error: Invalid URL type
    at run (/Users/jack/Sites/spotify-dl/cli.js:195:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
% spotifydl "test" --outputOnly
sdads true
⠋ Searching… Please be patient :)
⠼ Searching… Please be patient :)
Error: Invalid URL type
    at run (/Users/jack/Sites/spotify-dl/cli.js:195:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
```
% spotifydl "test" --output-only
sdads true
⠋ Searching… Please be patient :)
⠼ Searching… Please be patient :)
Error: Invalid URL type
    at run (/Users/jack/Sites/spotify-dl/cli.js:195:15)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by phyzical** [comment]
as for using the flags did you run --help?
