### ISSUE TITLE
Add Stalebot

### ISSUE THREAD

**Issue by phyzical** [SwapnilSoni1999/spotify-dl#108]
Hey there and thank you for using Issue Tracker!

## Checklist

- [x] Have a usage question? Review the readme first [Readme](./README.md). Search the issue and pull request history to see if someone else has had/having a similar issue to avoid duplicates

### Proposal
Lets integrate stable bot https://github.com/apps/stale
### Motivation
so that we can autoclose tickets that do not receive traction
### Outcome
stablebot makes things stale and autocloses :)

**Comment by phyzical** [comment]
@SwapnilSoni1999 what do you think?

**Comment by SwapnilSoni1999** [comment]
Good idea :)

**Comment by SwapnilSoni1999** [comment]
Also, I'm sorry for being late having really hard times nowdays

**Comment by phyzical** [comment]
@SwapnilSoni1999 no biggie, hope all is well

**Comment by SwapnilSoni1999** [comment]
I've added stale bot to my profile. We can now proceed with `stale.yml`
