### ISSUE TITLE
Error ! in downloading 404 code !

### ISSUE THREAD

**Issue by satyammayy** [SwapnilSoni1999/spotify-dl#109]

**Comment by satyammayy** [comment]
Input stream error: Status code: 404

**Comment by phyzical** [comment]
this was an issue with yt-dlcore (see https://github.com/fent/node-ytdl-core/pull/938) itself #106 has an updated package lock to fix the issue

**Comment by SwapnilSoni1999** [comment]
Hopefully the issue is fixed. Please let me know @satyammayy
