### ISSUE TITLE
Spotifydl no longer makes 1 folder for that playlist 

### ISSUE THREAD

**Issue by theofficialgrand1** [SwapnilSoni1999/spotify-dl#110]
When downloading Spotify playlist, Spotifydl places the music in multiple different folders sorted by the artist.

**Comment by phyzical** [comment]
This is correct behavior at this time, this was done to reduce duplicate downloads i.e downloading music from multiple playlists

if you would like the original functionality simply provide `spotifydl --oo -o "./playlist-name" "spotify-playlist-url"`
