### ISSUE TITLE
Can't download podcast

### ISSUE THREAD

**Issue by tejaschauhan373** [SwapnilSoni1999/spotify-dl#112]
It gives error as below while downloading podcast

![image](https://user-images.githubusercontent.com/59693377/124460054-81662300-ddac-11eb-806a-e1f7767f9e71.png)

**Comment by phyzical** [comment]
Hey there @tejaschauhan373  next time please use the template provided :)

Atm the episode urls type are not supported,
but we can look at adding them at some point in the near future

**Comment by tejaschauhan373** [comment]
sure & thanks for reply, can you add separate label like question, feature suggestion & bug report for issue !

**Comment by phyzical** [comment]
good idea!

cc @SwapnilSoni1999

**Comment by SwapnilSoni1999** [comment]
> good idea!
> 
> cc @SwapnilSoni1999

Added issue templates :)

**Comment by tejaschauhan373** [comment]
Also, you can make discord server to prevent creation of unnecessary issues for questions

**Comment by SwapnilSoni1999** [comment]
> Also, you can make discord server to prevent creation of unnecessary issues for questions

I dont use discord much though but still issues and PRs wont be any issues for me :) feel free to ask or make any issue if you want to

**Comment by phyzical** [comment]
@tejaschauhan373 i should have implemented this login in #115  pr if you wanted to give it a try, otherwise it should make it in a future version soon
