### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by lodembeep** [SwapnilSoni1999/spotify-dl#114]
**Describe the bug**
Once a specific song is downloaded, it just throws a type error. The song in question doesn't have any metadata.

**To Reproduce**
1. create a new folder
2. get into it
3. run : spotifydl -o LND https://open.spotify.com/playlist/0aJyer4nHU7lPMHIJR5dTY

**Expected behavior**
Should download the full playlist.

**Screenshots**
not required

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04LTS
 - Browser : doesn't matter
 - Version : Doesn't matter

**Additional context**
Here is the full response : 

ℹ Downloading: LDN Classics - misssmokingkills
ℹ Total Songs: 136
ℹ 55/136
Artist: 
Album: 
Song: UYCD003 Douglas Greed feat Delhia de France - Sense (André Lodemann Remix)
✔ Download completed.
TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received undefined
    at validateString (internal/validators.js:120:11)
    at Url.parse (url.js:160:3)
    at Object.urlParse [as parse] (url.js:155:13)
    at dispatchHttpRequest (/usr/lib/node_modules/spotify-dl/node_modules/axios/lib/adapters/http.js:91:22)
    at new Promise (<anonymous>)
    at httpAdapter (/usr/lib/node_modules/spotify-dl/node_modules/axios/lib/adapters/http.js:46:10)
    at dispatchRequest (/usr/lib/node_modules/spotify-dl/node_modules/axios/lib/core/dispatchRequest.js:52:10)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async downloadAndSaveCover (/usr/lib/node_modules/spotify-dl/lib/metadata.js:9:17)

**Comment by lodembeep** [comment]
I suggest to add a way to keep downloading the tracks with a downloading report showing the songs it didn't download

**Comment by phyzical** [comment]
hey @lodembeep, thanks for the issue report

i think that would be a good idea to report on the songs that fail,
I was thinking we could save a timestamped file with a list of rows containing "SPOTIFY_ID - ITEM_NAME - ITEM_LIST"
what do you think @lodembeep 

as for stopping a download when no metadata, i would say that's a regression i've caused in the last few pushes of changes.
I agree if metadata fails it should not stop downloading the playlist.

I will try to replicate your failure given the link provided, and try to implement the above

**Comment by lodembeep** [comment]
Thank you @phyzical !
About the reporting, i am not sure whether it is relevant or not, as some of the songs might not even exist in youtube or other sources, the decision is yours.

I tried with your fork, still doesn't want to download it, same issue and error. i will wait for the PR to be merged and try again on a clean install.

**Comment by phyzical** [comment]
@lodembeep a download report is now posted at the end of all requested urls, which will post any failures 
![image](https://user-images.githubusercontent.com/5182053/125189185-65112d00-e269-11eb-9589-b64cfa865d5c.png)
