### ISSUE TITLE
Sometimes it downloads the YouTube version of the song

### ISSUE THREAD

**Issue by koizumihoshino** [SwapnilSoni1999/spotify-dl#117]
**Describe the bug**
I try to download an album that has a short version released on YouTube but Spotify has the full version.

**To Reproduce**
Run
`spotifydl https://open.spotify.com/album/6yKMo95JkibE9tGN81dgFh?si=-Vh4RAjzTfa3kJNYIW7Tdg&utm_source=copy-link&dl_branch=1`
2. play it

**Expected behavior**
SpotifyDL should download the Spotify version since there are only short versions or the one that has breaks and stuff.

**Screenshots**
See attached.
Length of the song in Spotify:
![Screenshot_2021-07-12-08-40-46-822_com.spotify.music.jpg](https://user-images.githubusercontent.com/87285751/125215124-07262900-e2ed-11eb-8dff-f167f94b8d58.jpg)

Length of the song downloaded (YouTube/Short ver.)
![Screenshot_2021-07-12-08-40-58-470_com.miui.player.jpg](https://user-images.githubusercontent.com/87285751/125215138-14431800-e2ed-11eb-9a34-e5c60e039be5.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 AI
 - OS: MIUI 12 | Android 10
 - Terminal: Termux
 - Version: latest

**Additional context**
**_After digging into my downloads, I realized that it downloads YouTube versions of the songs, not on the Spotify one._**

**Comment by koizumihoshino** [comment]
I will try to replicate this issue on the PC later since I just woke up.

**Comment by phyzical** [comment]
this one is a hard one, as we do not download/ copy anything from spotify directly. we take the api information from spotify and search youtube and it just does a "best match" i.e `song - album` in youtube and downloads the first result.

my only suggestion would be to add the `additional search` param to try to make your spotify  -> youtube results more specific

**Comment by koizumihoshino** [comment]
Thank you! I will close this now.
