### ISSUE TITLE
Missing Artist Metadata

### ISSUE THREAD

**Issue by koizumihoshino** [SwapnilSoni1999/spotify-dl#118]
**Describe the bug**
When a song has multiple artists, SpotifyDL only puts the first mentioned artist.

**To Reproduce**
1. Run `spotifydl https://open.spotify.com/track/5O3zXdlwLUhMzYtJMQJEZ3?si=NanTyb14R0atEqq9CRTo9w&utm_source=copy-link&dl_branch=1`
2. See song metadata

**Expected behavior**
The song should have mentioned all the artists in the song.

**Screenshots**
See attached.
Metadata expected:
![IMG_20210712_083648.jpg](https://user-images.githubusercontent.com/87285751/125214961-56b82500-e2ec-11eb-8528-472c39aefccd.jpg)

Metadata SpotifyDL recognized:
![IMG_20210712_082954.jpg](https://user-images.githubusercontent.com/87285751/125214891-093bb800-e2ec-11eb-9dea-5e759e29e6b7.jpg)

**Smartphone (please complete the following information):**
 - Device: Xiaomi Redmi Note 5 AI
 - OS: MIUI 12 | Android 10
 - Terminal: Termux
 - Version: latest

**Additional context**
Not only in the given song, but at every song with multiple artists.

**Comment by phyzical** [comment]
hey there @koizumihoshino, 

just for clarification its more about the metadata than the log you care about correct?

ive made a change in mt latest pr that will save all artists metadata as it did in the  past. but to be clear it will still output only the first artist in logs as its used for things like folders ect
