### ISSUE TITLE
SpotifyDL deletes existing songs on Windows but in Android it doesn't.

### ISSUE THREAD

**Issue by koizumihoshino** [SwapnilSoni1999/spotify-dl#120]
**Describe the bug**
When I tried SpotifyDL on my PC, it restarted the download so I was confused why, I saw my past downloads gone and blank. Then I look at the terminal again and it was downloading from the beginning.

**To Reproduce**

On Android
1. Open Termux
2. CD to somewhere (I did `cd storage/shared/Spotify`)
3. Download a random song/album/playlist on Termux `spotifydl "song/album/playlist link"`
4. Copy the downloaded stuff to Windows

On Windows
1. Open Command prompt
2. CD to the root folder of the downloaded stuff (I did `cd Desktop/Spotify`)
3. Download the same random song/album/playlist `spotifydl "song/album/playlist link"`
4. Witness

**Expected behavior**
SpotifyDL skips the downloaded songs and downloads the missing/corrupt songs instead

**Desktop (please complete the following information):**
 - OS: Windows 8.1 Pro
 - Browser: doesn't matter
 - Version: doesn't matter

**Additional context**
none for now

**Comment by phyzical** [comment]
@koizumihoshino hey there, is it possible that you have different versions running on the android vs windows devices?

after it downloaded on windows did you end up with duplicates in the cache file?

one test we could try is to be explicit about the cache file with `--cf /PATH/TO/FILE.txt` on both devices and see if it makes any difference?

**Comment by koizumihoshino** [comment]
Oh i need to have the cache file? I thought spotifydl detects the songs that are already downloaded. I guess not.

**Comment by phyzical** [comment]
what it does is it saves a reference to the spotify song id to the`.spdlcache` files, it reads these files to determine if a song needs redownloading or not rather than the filenames themselves.

**Comment by koizumihoshino** [comment]
Ok, so my confusion is gone and I will make sure to copy the cache files too, thanks! (Please close this if needed since idk how to close on mobile.)
