### ISSUE TITLE
error code 1

### ISSUE THREAD

**Issue by Minehors** [SwapnilSoni1999/spotify-dl#122]
[npm-debug.log](https://github.com/SwapnilSoni1999/spotify-dl/files/6817967/npm-debug.log)
**Describe the bug**
ive included the npm-debug file in this post

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [win7]
 - Browser [firfox]
 - Version [latest version of firefox]

**Additional context**

**Comment by phyzical** [comment]
hey there @Minehors do you mind trying the following command? `npm install -g spotify-dl --unsafe-perm`
