### ISSUE TITLE
force download

### ISSUE THREAD

**Issue by godspeedfw** [SwapnilSoni1999/spotify-dl#126]
**Describe the bug**
after downloading a song, if you delete it and try to download it again, it will say "All songs already downloaded.."

**To Reproduce**
1. Download a song
2. Delete it
3. Try downloading the same song again

**Expected behavior**
Download the song

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version 1.0.2

**Additional context**
I think it saves a list of the downloaded songs somewhere in cache but checks the download argument against it. Maybe prompt the user if they want to force download [y/n] ?

**Comment by koizumihoshino** [comment]
Yeah there's a cache to it, here's how to fix it, just download that one song to a different location. Like, CD somewhere else.

**Comment by godspeedfw** [comment]
I see. Okay. Btw, where is the cache stored?

**Comment by phyzical** [comment]
by default it is stored in the folder in question .splcache

you can provide the --cf flag to override the default though

**Comment by godspeedfw** [comment]
thanks! that is exactly what i needed
