### ISSUE TITLE
I am noob don't know what to do please guide me

### ISSUE THREAD

**Issue by rayand652** [SwapnilSoni1999/spotify-dl#130]
![IMG_20210805_164456](https://user-images.githubusercontent.com/79494339/128341552-05fea156-10a7-4513-8b60-811761cefc83.jpg)

I am a noob please guide me

**Comment by SwapnilSoni1999** [comment]
can you please show output of `node --version` and `npm --version`

**Comment by rayand652** [comment]
![IMG_20210822_193800](https://user-images.githubusercontent.com/79494339/130358166-eb0de80d-e7be-48cd-96ae-819b467f10df.jpg)

**Comment by SwapnilSoni1999** [comment]
Can you please try to upgrade npm and node versions and uninstall spotify-dl and reinstall it?

**Comment by rayand652** [comment]
When I tried to build docker image it asked me to install git so I gave the command pkg install git and it showed me this
![IMG_20210828_231501](https://user-images.githubusercontent.com/79494339/131226445-72e79f9b-9f3b-4b28-81a9-9dd6a4631d7e.jpg)

**Comment by rayand652** [comment]
Sir can you please tell me what is the problem here and how can I resolve it
![IMG_20210828_233137](https://user-images.githubusercontent.com/79494339/131226817-cc53f3d3-1fb9-497f-9cc5-e0567c6220df.jpg)

**Comment by SwapnilSoni1999** [comment]
@phyzical can you please look into this? I'm on iOS right now

**Comment by phyzical** [comment]
@SwapnilSoni1999 i think this is a similar issue to #134 and #132 once we have bumped to a new version i think this should be fixed

**Comment by rayand652** [comment]
So what should I do now?

**Comment by rayand652** [comment]
Is this issue fixed now?

**Comment by phyzical** [comment]
could you try updating to the latest and letting us know @rayand652
