### ISSUE TITLE
Error displaying when trying to download or check version being used 

### ISSUE THREAD

**Issue by Xmetalfanx** [SwapnilSoni1999/spotify-dl#132]
**Describe the bug**
After installing via NPM or (after removing via NPM) the manual method, I see this 
when i run any command ... including "spotifydl <link here>" ... I am just using the -v option below as the example but it's exactly the same message no matter what flag i use or actual spotify URL i use 

```
spotifydl --version                                                                              Tue 17 Aug 2021 09:35:44 PM EDT
/home/xmetal/spotify-dl/lib/setup.js:3
const meow = require('meow');
             ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/xmetal/spotify-dl/node_modules/meow/index.js from /home/xmetal/spotify-dl/lib/setup.js not supported.
Instead change the require of index.js in /home/xmetal/spotify-dl/lib/setup.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/xmetal/spotify-dl/lib/setup.js:3:14)
    at Object.<anonymous> (/home/xmetal/spotify-dl/cli.js:17:21) {
  code: 'ERR_REQUIRE_ESM'

```

**To Reproduce**
1. Install spotifydl (either via npm or the manual method posted)
2. Running spotifydl with any URL or even the flags to check the version, result in the same message

**Expected behavior**
Spoifydl either starting the download or display the version being used 

**Desktop (please complete the following information):**
 - OS: Manjaro Linux
 - Browser: Firefox
 - Version: ?? Updated as of a few hours ago, it's a rolling release based on Arch, so sometimes versions numbers are not used as much as other distros

**Additional context**
I do have other distros on different systems, so i am not sure if this is specific to Manjaro or my setup, but I have used this before and it's been just fine ... just tonight when I went to use spotifydl and happen to be in an updated (I have not rebooted since the last updates I admit) version of Manjaro Linux right now.   Right now i can't "test" other distros to see if happening on them too

**Comment by phyzical** [comment]
@Xmetalfanx thanks for the bug report, what version of npm and node are you using?

**Comment by TwistyDev** [comment]
I have the exact same issue on Manjaro (with the latest updates). Node v16.6.2 and npm v7.21.0. Don't know the version of spotifydl as it crashes, but I guess it is the latest from npm. 
I am sure it is the spotifydl update that broke it, as it worked perfectly before I ran 'npm -g spotifydl' 2min ago.

**Comment by Xmetalfanx** [comment]
node v16.6.2
npm 7.20.6

i admit i haven't updated in the last 2 days but as you can see someone else has a slightly more updated version of npm than i have atm

**Comment by phyzical** [comment]
Thanks for all of that,

i was able to replicate it.

 i'm not sure why it wasn't happening locally.. but should hopefully be fixed with the next release.

**Comment by Xmetalfanx** [comment]
can COMFIRM this issue is now fixed for me on Manjaro

**Comment by SwapnilSoni1999** [comment]
Awesome <3
