### ISSUE TITLE
 Only file and data URLs are supported by the default ESM loader. Received protocol 'node:'

### ISSUE THREAD

**Issue by ArcerionDev** [SwapnilSoni1999/spotify-dl#136]
Error -
![image](https://user-images.githubusercontent.com/60945964/133100548-b8700178-ca91-40f0-99f3-b72a791c24e9.png)

node v14.12.0
npm v6.14.8

**Comment by phyzical** [comment]
@ArcerionDev thanks for posting.

Could you please paste the exact link that fails incase its related but,

i just tried the latest on windows and tried a playlist and a song and all seems to work fine.
