### ISSUE TITLE
WHERE DOES THE DOWNLOAD SAVE AT?

### ISSUE THREAD

**Issue by bBSempai** [SwapnilSoni1999/spotify-dl#137]
I downloaded something but i dont know where it got saved. WHERE DO ALL THE SONGS GET SAVED??

**Comment by phyzical** [comment]
hey @bBSempai it should be relative to wherever its run from but you can overide it with the `-o` flag

**Comment by SwapnilSoni1999** [comment]
you can use `-o` flag to define an output folder. The similar issue is here #110

**Comment by Abzolutely** [comment]
Yes but where exactly? 
Ps: I'm using termux on android

**Comment by SwapnilSoni1999** [comment]
> Yes but where exactly? Like where is the file that is stored in? It is not shown on my device Ps: I'm using termux on android

you can check by typing `ls` command 
use this command wherever you used the `spotifydl` command in termux path

**Comment by Abzolutely** [comment]
> > Yes but where exactly? Like where is the file that is stored in? It is not shown on my device Ps: I'm using termux on android
> 
> you can check by typing `ls` command 
> use this command wherever you used the `spotifydl` command in termux path
>  

Ok I figured that out thanks 

But there is an issue when I try to download a whole playlist, it just download a part of a song and then the terminal shows that it's done

**Comment by SwapnilSoni1999** [comment]
> > > Yes but where exactly? Like where is the file that is stored in? It is not shown on my device Ps: I'm using termux on android
> > 
> > 
> > you can check by typing `ls` command
> > use this command wherever you used the `spotifydl` command in termux path
> 
> Ok I figured that out thanks
> 
> But there is an issue when I try to download a whole playlist, it just download a part of a song and then the terminal shows that it's done

can you share the link of the playlist

**Comment by Abzolutely** [comment]
> > > > Yes but where exactly? Like where is the file that is stored in? It is not shown on my device Ps: I'm using termux on android
> > > 
> > > 
> > > you can check by typing `ls` command
> > > use this command wherever you used the `spotifydl` command in termux path
> > 
> > Ok I figured that out thanks
> > 
> > But there is an issue when I try to download a whole playlist, it just download a part of a song and then the terminal shows that it's done
> 
> can you share the link of the playlist

https://open.spotify.com/playlist/3o8vXXLGb6YyaA6E1On17N?si=Juk6PwpTTWy3NDC14htIAw&utm_source=copy-link 

Here it is

**Comment by Soulplayer** [comment]
what is the right flag for the docker output?
