### ISSUE TITLE
feat: Add support for parallel downloads

### ISSUE THREAD

**Issue by nij4t** [SwapnilSoni1999/spotify-dl#14]
When downloading albums/playlists the app can handle only one track at a time.  Once it finishes downloading that track it switches to another one in the queue.
Using nodejs workers that was introduced in v10 can be used to delegate downloading of tracks to a dedicated thread. Another way of implementing that feature is to use process forks to support older versions of nodejs.

**Comment by SwapnilSoni1999** [comment]
Seems good though, will work on it. <3
