### ISSUE TITLE
Download source

### ISSUE THREAD

**Issue by forscht** [SwapnilSoni1999/spotify-dl#140]
**Q:** Does it download songs from Spotify or YouTube? I'm looking for best quality possible. Can we also update README so others don't get confused? Or once I will get answer I will open PR.

**Comment by phyzical** [comment]
hey @forscht this uses the spotify api to gather track information then perform a youtube search and then pulls down the audio of the most relevant found youtube video

from the readme 

```
spotifydl

A simple commandline utility that allows you to download Spotify Songs, Shows, Episodes, Playlists and Albums from Youtube.
```

But feel free to open a pr to improve anything you find that counters the above :)
