### ISSUE TITLE
Downloads Music Video, not the song

### ISSUE THREAD

**Issue by PiSaucer** [SwapnilSoni1999/spotify-dl#144]
**Describe the bug**
Almost every song that is downloaded is the music video of the song. It's not the normal song.

**To Reproduce**
1. Download Any Song

**Expected behavior**
I thought it would compare the times to select the non-music video version.

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Python: 3.8.1
 - Verison: 1.0.5
 
**Possible Solution**
Compare the times from the Spotify API to youtube-dl.

**Comment by phyzical** [comment]
hmm @PiSaucer thanks for this, i guess i honestly have never checked if it was getting a music video vs a non music video,

i would proably argue its due to the fact the youtube API returns the "most relevant" which is probably the music video.

There is a few ways around this.

* we can look at improving the youtube matching (to be honest this is very dumb atm) (Help welcome)
* you can use the param that adds search strings tot he youtube api calls if there's some magic keyword to avoid music videos

**Comment by phyzical** [comment]
not yet

**Comment by Xmetalfanx** [comment]
I have to admit I have not used this script/app in a little bit but this did not happen to me when i first discovered Spofity-dl but the last few times i used it, this would happen to me too ... it seemed like it was defaulting to the Youtube video first, as some tracks had something at the start or ending (before any music) that was clear that it was the video version of the song.   

It did download the audio for that say YT video fine, but that is not what I had expected (again if there was the artist talking before or after the music, or some intro that was not in the song's album version on Spotify .... this is sort of a song-to-song type thing, depending on what someone is trying to download)

**Comment by phyzical** [comment]
@Xmetalfanx thanks for the input, did you happen to be searching the exact same search terms? its possible you were just lucky the first time. though maybe ill have a sniff around the YT stuff and see if there was something thats now favoring music videos. but again i think its just the fact that music videos of songs get more views and thus are higher in the list to get auto downloaded.

we could consider maybe doing a pre filter to only fall back to a result with "music video" or something in the title if nothing else is found, but that may also lead to an incorrect match being downloaded instead

**Comment by Niloc3** [comment]
having this same issue, what search term do you think would help avoid music videos and just get the song? I haven't looked at the YouTube api in forever so not sure if it's possible but being able to search for videos that don't include "Music Video" could help a ton if possible.

**Comment by phyzical** [comment]
@Niloc3 i had a look when i was applying the suggested functionality update from above, sadly there isn't any such functionality in the api itself there are just videos. its just getting the most relevant/most popular and that happens to be music videos

**Comment by Niloc3** [comment]
@phyzical thanks for the info, I guess the music video is the best we got

**Comment by arinoki** [comment]
> 

well, best one is still webm (ogg) 128kbps we can get from utube - so doesnt really matter music video or not. the only exception is live videos for obvious reasons.

**Comment by phyzical** [comment]
if anyone notices a common piece of text in the title i can look into adding a "exclude filter" flag also,say if they all contained "live" or something it would justify the requirement to add the feature

**Comment by arinoki** [comment]
> if anyone notices a common piece of text in the title i can look into adding a "exclude filter" flag also,say if they all contained "live" or something it would justify the requirement to add the feature

well, "live", "concert", "club" is first words that keep in mind. probably "cover" too if we wanna original. but we have a lot of covers on spotify aswell, so need double-check.

**Comment by arinoki** [comment]
is there some kind of DMs? cause i cant find.

**Comment by arinoki** [comment]
> if anyone notices a common piece of text in the title i can look into adding a "exclude filter" flag also,say if they all contained "live" or something it would justify the requirement to add the feature

ok, just add me on discord - Sora-#8039 and we will make brainstorm about filter words

**Comment by phyzical** [comment]
Sorry what i meant was if you find these as common tags, then ill just make the feature so users can provide filter text i.e if any text that matches any filters are found as a whole word, check the next video 

Blah LIVE song X
Blah Concert song X
Blah Song X

and so if the user provided say `--filter="LIVE, Concert"` it would skip the first two and return the third.

just wanted to confirm it would even be useful before implementing

**Comment by arinoki** [comment]
> Sorry what i meant was if you find these as common tags, then ill just make the feature so users can provide filter text i.e if any text that matches any filters are found as a whole word, check the next video
> 
> Blah LIVE song X Blah Concert song X Blah Song X
> 
> and so if the user provided say `--filter="LIVE, Concert"` it would skip the first two and return the third.
> 
> just wanted to confirm it would even be useful before implementing

I think overall this will be used by <1% of users, but overall its up to u if implement or not.

**Comment by javalsai** [comment]
I tried to fix this by preferring the download of songs with a the duration more close to the original song from spotify.

I did it in [my own fork of the project](https://github.com/javalsai/spotify-dl), and it works with half of some songs [that I know are problematic](https://open.spotify.com/playlist/3JXIuSvkf6JDLUf4p8bWTH?si=905b6bf3f3424e33), I guess that I should add more sorting preference like that the youtube channel matches the song artist...

If I make it work fine with that playlist and you want I will create a PR

**Comment by phyzical** [comment]
@javalsai Sure, good idea! 

did you notice any issues going with this approach?

**Comment by javalsai** [comment]
@phyzical yes, I ended up including more factors like the channel name... and giving more "points" according to them.

The problems come with songs like "Fluorescent Adolescent - Artic Monkeys" that isn't uploaded to their official channel and other songs that are in the channel get more points, this can be solved by playing with the importance of each of those factors and the current values kinda do the job.

I will do a bit of more testing with them, but in my opinion the current ones work enough good.
