### ISSUE TITLE
Login stuck at "You agree that spotify-dl will be able to" screen

### ISSUE THREAD

**Issue by SokolskyNikita** [SwapnilSoni1999/spotify-dl#152]
**Describe the bug**
Auth fails because spotify-dl can't get past the "You agree that spotify-dl will be able to" screen. See attached `failure.png`

**To Reproduce**
1. Download spotify-dl (I've used the npm version)
2. Try to download a podcast episode

**Expected behavior**
Auth succeeds

**Screenshots**
![failure](https://user-images.githubusercontent.com/1880652/158076817-c5dcbf0f-b667-4ecf-91cd-918ff801f331.png)

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: no browser window is visible, not sure what spotify-dl is trying to do in background
 - Version: 1.0.7

**Comment by phyzical** [comment]
hmm i might not have added logic to auto click this (i guess i dont think we should, force the user to accept it manually but docs should be updated to enform users of this).

are you providing the `--u` and `--p`? that uses headless to to try and login for you what you can use instead is use the `--l` flag which will serve it via a browser instead

**Comment by SokolskyNikita** [comment]
You're right, `--l` does work. But I think at least adding a warning about why it fails could be useful if you don't want to click on Agree.

**Comment by phyzical** [comment]
you have to agree its just saying "this app needs access toy our playlists ect", but i agree we need to add some more to the readme to inform users :) will do it later today
