### ISSUE TITLE
Docker: Stuck at "Performing Spotify Auth Please Wait..." 

### ISSUE THREAD

**Issue by maej20** [SwapnilSoni1999/spotify-dl#156]
**Q:**
I'm trying to use the -login flag, but I'm never prompted with a login form.
Command being run: `docker run -it --user=$(id -u):$(id -g) -v $(pwd)/downloads:/download --rm spotify-dl --l $URL`
What am I doing wrong?

**Comment by phyzical** [comment]
i might have to update the documentation, so the issue here is you cant use --l at all with docker as well theres no "screen"
```
To use --u and --p (headless login) you must do a --l once first to grant required permissions (playlists, saved songs ect.)
```

you can try --u and --p, if it doesnt work i suggest running --l without docker once to authorise the app and then --u --p should work fine with docker

**Comment by phyzical** [comment]
closable
