### ISSUE TITLE
Add track number metadata to downloaded tracks

### ISSUE THREAD

**Issue by vvatermelon** [SwapnilSoni1999/spotify-dl#163]
**Is your feature request related to a problem? Please describe.**
In my use case, this tool works exceptionally well but I have to manually add track numbers to downloaded albums in order to preserve the original order of the album. In a small scope this is reasonable, but at scale it seems logical to integrate into the merge metadata step.

**Describe the solution you'd like**
I think an extra option like '--preserve-track-order' or something of the sort could allow users the opportunity to preserve track order, otherwise if order is not important they could just omit it. I assume slight tweaks to util/runner.js and lib/metadata.js could allow the download index (currentCount) to be used as the track index (I am not very familiar with js).

**Describe alternatives you've considered**
Manually entering track numbers through any given file manager or creating another program to retroactively assign track order would accomplish the task.

**Additional context**
The ffmetadata package provides a 'track' key that could be assigned with the index of the song in the album it is downloaded for. I did not find any related suggestions so I hope this hasn't been addressed already. 🙂

**Comment by phyzical** [comment]
@vvatermelon hey there, thanks for the request and suggestions of how to implement.

having a quick look we should have access to the track_number given all the search contexts from the api, so i will make a pr up to add it now :)

**Comment by phyzical** [comment]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/5182053/169244658-067a6e5b-8ecb-44fa-bd50-f4aff94463f3.png">
alright looks to be working doesn't report in generic "get info" for osx but other applications seem to respect this metadata hopefully whatever your using it for will too
