### ISSUE TITLE
Download 320Kbps

### ISSUE THREAD

**Issue by switch-gott** [SwapnilSoni1999/spotify-dl#165]
Hi,
is it possible to download with best quality settings oder 320kbps?
Big thanks

**Comment by arinoki** [comment]
Spotify-dl actually downloads from YouTube, and YouTube doesnt have mp3 at all. It uses mostly opus codec, rare - aac. 

As an example 
![image](https://user-images.githubusercontent.com/966158/170218577-75cea798-bf09-48f2-b7bc-5974467d6284.png)

**Comment by switch-gott** [comment]
Hi thanks for answer.
Oh ok. I thought it use direkt connection to spotify, no youtube dl.
Is it possible to download direct from spotify?
Have a look at this tool
https://github.com/eviabs/downtify-premium
Realy good one. And worked till last week.
I dont know what spotify had changed to kill it :-(

**Comment by phyzical** [comment]
Afraid direct from spotify isn't possible with this tool, sorry

**Comment by phyzical** [comment]
closable
