### ISSUE TITLE
Very Slow Download Speed

### ISSUE THREAD

**Issue by createvi** [SwapnilSoni1999/spotify-dl#166]
**Describe the bug**
Very Slow Download Speed. I have an internet speed of 18mbps download and upload but when i download a song playlist the network speed is very slow i am hardly getting 100kbps. Why is this happening? 

**To Reproduce**
1. Download Any Playlist/Album
2. See The Downloading Speed

**Expected behavior**
Songs Downloading Speed Should Be Higher.

**Desktop (please complete the following information):**
 - OS: MX Linux KDE
 - Browser Firefox
 - Version 1.0.8

**Comment by createvi** [comment]
```zsh
⠏ Trying youtube link 1...WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
```
This Shows Up Too, Everytime. i did what it said and it still shows up while downloading a song

**Comment by arinoki** [comment]
Can u link an example of slow playlist? So will check it on windows.

**Comment by createvi** [comment]
https://open.spotify.com/playlist/6u7VAC36wQF4gJ2mGEbnte
This is my own playlist.

**Comment by arinoki** [comment]
Well, different audio tracks different speed. But overall from 300 kbps to few mb. So cant say its too slow.
