### ISSUE TITLE
starting at a specific song

### ISSUE THREAD

**Issue by StarNumber12046** [SwapnilSoni1999/spotify-dl#168]
**Is your feature request related to a problem? Please describe.**
Ihave a VERY long playlist 8about 400 songs) and I would like to download only the last 70 songs
**Describe the solution you'd like**
I would like to let the dowloader start from a specific songs 

**Describe alternatives you've considered**
Downloading from a list of titles

**Additional context**
![image](https://user-images.githubusercontent.com/64470722/179478884-d93c4acc-104d-4aa1-9eeb-a61f35752edd.png)

**Comment by phyzical** [comment]
im not sure if we really get the songs in the correct order, but one workaround would be to add the other 330 song ids into the cache file so it thinks they have already downloaded. though i cant think of a nice way to pull that off easily besides using the api yourself to get all the ids to exclude.

if your dev savvy at all https://developer.spotify.com/console/get-playlist-tracks/ would be the easiest way

**Comment by StarNumber12046** [comment]
Thanks for the reply, it seems to me to retrieve the songs in order btw I will try to do it manually

**Comment by phyzical** [comment]
ah fair enough, i guess to give the suggestion a fair play out how would this new feature flag work? maybe  `--song-range 3,10` or for your case `--song-range 330,n`

this could work for the specific case of a single show, album or playlist. but im just wondering how useful it would be to others as most just try to gulp it all.

we can leave this open to see if any other interest comes in and readdress then :) good luck!

**Comment by StarNumber12046** [comment]
this implementation prototype seems good to me, it could be used
