### ISSUE TITLE
Covers of songs have `EOI missing` (according to ffprobe)

### ISSUE THREAD

**Issue by javalsai** [SwapnilSoni1999/spotify-dl#171]
**Describe the bug**
Most of the covers of the songs have `EOI` missing (according to ffprobe), which means that the image is corrupt or didn't finish downloading when being added to the song. This leads to the image not displaying correctly on file managers, music players...

**To Reproduce**
1. Download any playlist with the spotify-dl cli and most images should be like this.

**Expected behavior**
Images fine added to the song.

**Screenshots**
![image](https://user-images.githubusercontent.com/80113062/182052256-407b4ea4-3d36-4474-acb3-ceac5c706691.png)
![image](https://user-images.githubusercontent.com/80113062/182052225-7e4e9fe8-ba0b-4363-9a5a-14f418c59612.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.18.14-arch1-1)
 - Browser Firefox (Mozilla Firefox 103.0)
 - spotify-dl version: 1.0.8

**Comment by javalsai** [comment]
Not sure if it is because of this, but assuming that the cover is a `jpg` isn't probably a good idea.
https://github.com/SwapnilSoni1999/spotify-dl/blob/09b803f4225e7d85e5304e220ae90fabaa8b787e/lib/metadata.js#L8-L31

**Comment by phyzical** [comment]
feel free to give `png` a try, from memory it had to be a `jpg` but i could be wrong

**Comment by javalsai** [comment]
@phyzical I see that for audio download you use ffmpeg to make sure of the format, as far as I know ffmpeg also works with images, so I'm giving it a try

**Comment by javalsai** [comment]
Seems to be working, I'll download a full playlist and if it does work I'll open a PR
