### ISSUE TITLE
Is there a way to skip songs in a playlist from downloading again?

### ISSUE THREAD

**Issue by thribhuvanrapolu** [SwapnilSoni1999/spotify-dl#173]
So I downloaded a playlist. After few days i added few songs into my playlist on spotify. When i download the playlist all the songs which are downloaded are downloaded again and getting replaced. Is there a way to prevent this?

**Comment by phyzical** [comment]
there is a file that saves the unique id of a song `.spldcache` or something like that byt default, just provide the `--cf /directory/to/file.txt` flag and it will use this file instead as your "remember what ive downloaded`.

**Comment by thribhuvanrapolu** [comment]
Got it. Thanks!
