### ISSUE TITLE
Couldn't find ffmpeg. Please install https://ffmpeg.org

### ISSUE THREAD

**Issue by MaitreGEEK** [SwapnilSoni1999/spotify-dl#174]
**Q:** The module ask me to install ffmpeg but it is already installed and the folder ffmpeg is in the same folder when I do the command.

**Comment by MaitreGEEK** [comment]
![image](https://user-images.githubusercontent.com/90345438/188327531-ccc3495a-4bd8-4ae3-86bf-6047d8f53ae2.png)
(I modified to see the error : 
![image](https://user-images.githubusercontent.com/90345438/188327554-9a84151b-4b61-4d33-8911-df140786cbe4.png)
)

**Comment by phyzical** [comment]
hey @MaitreGEEK

could you try `where ffmpeg` in a cmd prompt im guessing ffmpeg isnt in your class path?

**Comment by MaitreGEEK** [comment]
I m getting the same error as above "INFO: Could not find files for the given pattern(s)." My ffmpeg is in C:\Users\%USER%\AppData\Roaming\nvm\v18.7.0\node_modules

**Comment by phyzical** [comment]
so yeah the ffmpeg needs to be findable by your system

https://www.wikihow.com/Install-FFmpeg-on-Windows
see step 12

**Comment by MaitreGEEK** [comment]
Well, okay I see, thanks.

**Comment by SwapnilSoni1999** [comment]
solved? all good?

**Comment by MaitreGEEK** [comment]
I think yes, I didn’t try but I think this is link with the fact that I’m using nvm. It worked on my phone (not with your specific thing for termux but with spotifydl (link) From: Swapnil SoniSent: Wednesday, September 14, 2022 12:50 AMTo: SwapnilSoni1999/spotify-dlCc: MaîtreGEEK; MentionSubject: Re: [SwapnilSoni1999/spotify-dl] Couldn't find ffmpeg. Please install https://ffmpeg.org (Issue #174) solved? all good?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by SwapnilSoni1999** [comment]
So should I close this?

**Comment by MaitreGEEK** [comment]
Yes, do it.

Le ven. 7 oct. 2022, 20:17, Swapnil Soni ***@***.***> a
écrit :

**Comment by SwapnilSoni1999** [comment]
Much thanks
