### ISSUE TITLE
A wrong song is downloaded

### ISSUE THREAD

**Issue by HannesDev** [SwapnilSoni1999/spotify-dl#175]
**Describe the bug**
A different song is downloaded.
Meta data and album cover and all is correct, but the song is a complete different one.

Interestingly the same issue happens with a different song from the album, which also downloads the same (wrong) song as the first one.

**To Reproduce**
1. `spotifydl "https://open.spotify.com/track/6PqDGnI0FKH8OjkwozU4MU?si=dae3dbd111004b9d"`
2. Listen to the song and compare with the one from Spotify - it's a different one.

1. `spotifydl "https://open.spotify.com/track/2J6QeBYm6U98WkiMs5Z2cU?si=fbec4ea1690a4de9"`
2. Again, a different song is downloaded - the same as the first one. Both are incorrect though.

**Desktop (please complete the following information):**
 - OS: macOS 12.6
 - Version: 1.0.9

**Comment by HannesDev** [comment]
I just looked through the closed issues and learned that this tool actually downloads from Youtube, not Spotify. This is quite confusing - how about changing the readme so that this becomes more clear?

**Comment by arinoki** [comment]
Well, it is exactly in readme
"The ability to find a video is dependent on the fact it is hosted on **youtube**, and even then there is a chance it is still incorrectly matched"
