### ISSUE TITLE
Module Not Found on Termux for Android

### ISSUE THREAD

**Issue by SamuelSHrk** [SwapnilSoni1999/spotify-dl#178]
**Describe the bug**
Any Spotify link I use to share to Termux throws a module not found error

**To Reproduce**
1. Go to any album on Spotify
2. Click on Share
3. Select Termux

**Expected behavior**
The album should download as normal

**Screenshots**
![Screenshot_20221123-144012.png](https://user-images.githubusercontent.com/43790833/203633236-4a9e892f-e9d3-450b-8ef7-4f5b71f508a1.png)If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: Moto G Stylus 2021
 - OS: Android 11 rooted
 - Browser N/A
 - Version N/A

**Additional context**

**Comment by MeCorey** [comment]
- [ ] 
Ty... that's a strange one.
