### ISSUE TITLE
Skip ?si query param

### ISSUE THREAD

**Issue by vbouchet31** [SwapnilSoni1999/spotify-dl#180]
Thanks for building this tool.

I noticed that when I get the album link for the MacOS spotify app, I get a link with ?si query param:
https://open.spotify.com/album/0eW3xQ0udqg9RKJWAhUKxi?si=xXXXXxxx-xxxxXXXxx
(I am not really sure the purpose so I have changed the value).

```
% spotifydl https://open.spotify.com/album/4z87XV3cBhlLUtoY3dsd6q?si=xXXXXxxx-xxxxXXXxx
zsh: no matches found: https://open.spotify.com/album/4z87XV3cBhlLUtoY3dsd6q?si=xXXXXxxx-xxxxXXXxx
% spotifydl https://open.spotify.com/album/4z87XV3cBhlLUtoY3dsd6q                          
⠸ Searching… Please be patient :)
```

Would be great it does not take in account this param so we can simply copy/paste without altering the url (I know, I am lazy ;-) ).

**Comment by vbouchet31** [comment]
I realized that I am not using the latest version, I will try to update to see if it is already fixed.
```
% spotifydl --version
1.0.2
```

**Comment by phyzical** [comment]
i think this is a zsh thing i think if you just wrap the url in quotes it would work
