### ISSUE TITLE
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true npm install -g spotify-dl does not work and thus doesn't fix the puppeteer error

### ISSUE THREAD

**Issue by BlastkinS** [SwapnilSoni1999/spotify-dl#184]
i've tried multiple times to enter and modify the npm installation and skipping the puppeteer installation part but it just doesn't work.

**Comment by MeCorey** [comment]
> what version of node/npm?

Had to update. Ty for mentioning it I would have never looked 🙄
