### ISSUE TITLE
Command -l does not work

### ISSUE THREAD

**Issue by Sofiandsv** [SwapnilSoni1999/spotify-dl#186]
**Q:** What is the correct usage of --login? every time I use it it says "See spotifydl --help for instructions"

**Comment by phyzical** [comment]
it should just be `--login` without anything else this should then flick you over to spotify in your browser to perform a login, otherwise you can just provide `--username` and `--password` as an alternative

**Comment by SwapnilSoni1999** [comment]
> it should just be `--login` without anything else this should then flick you over to spotify in your browser to perform a login, otherwise you can just provide `--username` and `--password` as an alternative

You're saviour of this repo. *Bows*

**Comment by dreamflasher** [comment]
I can confirm this issue on Windows: 
`spotifydl -l` or `spotifydl --l` yields "See spotifydl --help for instructions"

While `spotifydl --l downloadurl` correctly opens the login.

**Comment by phyzical** [comment]
ahk what ill do is as a better error message saying "please provide a url for scaping"
