### ISSUE TITLE
Provide option to turn off youtube download

### ISSUE THREAD

**Issue by dreamflasher** [SwapnilSoni1999/spotify-dl#187]
**Is your feature request related to a problem? Please describe.**
When I download playlists, it always tries to download via youtube search first. This results in files I do not want.

**Describe the solution you'd like**
An option to turn that behaviour off.

**Describe alternatives you've considered**
alternativlos

**Additional context**

**Comment by dreamflasher** [comment]
Yeah, it's a bit weird, it looked like it sometimes would download directly from Spotify. Is there any library that can do that or are they all blocked by Spotify?

**Comment by phyzical** [comment]
there are some out there but they are frowned apon by spotify yeah. beware if you find something use throwaway accounts ect
