### ISSUE TITLE
Youtube error retrying download - Input stream error: Missing catch or finally after try

### ISSUE THREAD

**Issue by aallvi** [SwapnilSoni1999/spotify-dl#189]
**Describe the bug**
when i put 
spotifydl https://open.spotify.com/playlist/40HtNm9ICSIqwqMrThDbX9?si=b211f843e52f40bd --output C:\Users\alvar\Desktop\alvi\test
i get
Youtube error retrying download - Input stream error: Missing catch or finally after try

**To Reproduce**
only do the steps to use the program, and get the error

**Expected behavior**
download the song or playlist

**Screenshots**
https://i.postimg.cc/2ypTSpWh/spotierror.jpg

**Desktop (please complete the following information):**
windows, node 14

**Additional context**
I have a video tutorial using this package and i have no problem but today the people have this problem and i go to see what happen i get the same bug.

You can see my video with the package working fine, but now we have this bug
Link to my video on youtube
https://www.youtube.com/watch?v=NUbOPFiwdqs&t=1s

Thanks!

**Comment by phyzical** [comment]
@aallvi does this happen mid way through the playlist or on the first song it tries to scrape?

**Comment by phyzical** [comment]
@aallvi @parthpanchal3399 any chance you can try the current master branch? just noticed there was a duplicate issue.

but can confirm its working atm so maybe some node updates resolved this
