### ISSUE TITLE
Input stream error: Missing catch or finally after try. Youtube error retrying download.

### ISSUE THREAD

**Issue by parthpanchal3399** [SwapnilSoni1999/spotify-dl#190]
**Describe the bug**
Download fails with the following error: Input stream error: Missing catch or finally after try. Youtube error retrying download.
The link it produces is correct, but it cannot download the song.

**To Reproduce**
1. Run the song download command: `spotifydl -o C:\Users\Parth\Downloads\youtube-dl\downloaded --oo https://open.spotify.com/track/6Kynli1iHBqJRWUCohcV9h?si=821a533a5c294a21`
2. Wait for it to retry

**Expected behavior**
The song should be downloaded to the specified directory.

**Screenshots**
https://ibb.co/30Fhxc0
https://ibb.co/nwgZGw4

**Desktop (please complete the following information):**
 - OS: Windows 10 Home 21H2
 - Browser: Chrome 111.0.5563.147 (Official Build) (64-bit)
 - spotifydl Version: 1.1.0
 - ffmpeg version: ffmpeg version 2023-04-03-git-6941788d24-full_build-www.gyan.dev 
 - npm version: 9.5.1

**Additional context**
I believe this has something to do with the yt-dl/youtube-dl. Because I faced similar problem when trying to download songs using youtube-dl.

**Comment by phyzical** [comment]
@parthpanchal3399 any chance you can try the current master branch?

**Comment by parthpanchal3399** [comment]
Hello @phyzical,
Sorry for the late reply. I didn't have my laptop, so I couldn't try until now.

I cloned the master branch and manually installed using npm install, npm link.
I was able to download the song now.

![image](https://user-images.githubusercontent.com/51913848/236611569-34d63c36-d2dd-467c-9ccc-3d8b2c7af6d4.png)

Closing this issue. Thanks :)
