### ISSUE TITLE
Lyrics download

### ISSUE THREAD

**Issue by StarNumber12046** [SwapnilSoni1999/spotify-dl#191]
**Is your feature request related to a problem? Please describe.**
I like lyrics in songs and being able to automatically add them at download time would be nice

**Describe the solution you'd like**
Addition of lyrics via id3? at download / merge time
**Describe alternatives you've considered**
Adding lyrics by hand (painful)

**Additional context**

**Comment by phyzical** [comment]
This should be possible, but it would be relying on whatever subtitles youtube stores for the video. ill have a look to see if spotify offers something in the api for lyrics but ive got a feeling thatll be a nogo

**Comment by StarNumber12046** [comment]
maybe with lyrics.com or musixmatch

**Comment by phyzical** [comment]
i ended up using genius, atm there is now functionality in master which when you provide `--dl` it will download the lyrics and save it as a txt file with the same name as the song. will have to wait for the owner of the repo to publish a new version or just clone master and run the `cli.js` if you want to try it out sooner.

lmk if this isnt want you were after

**Comment by phyzical** [comment]
ah i see you requested id3 metadata not just the lyrics im not super familiar so ill have to do a bit more reading on this..

**Comment by phyzical** [comment]
@StarNumber12046 master now has the functionality to embed the lyrics though they are unsynced.

i also added bpm and rating (rating is only support by some players though)
![image](https://user-images.githubusercontent.com/5182053/233778094-1417ba42-01a7-46b7-92f8-56f56c9bb4fb.png)

**Comment by StarNumber12046** [comment]
Gg

**Comment by StarNumber12046** [comment]
Also which player are you using?

**Comment by phyzical** [comment]
that's just itunes, but i also tested foobar
