### ISSUE TITLE
 Youtube error retrying download i Input stream error: Invalid regular expression: missing /

### ISSUE THREAD

**Issue by Starlord-199** [SwapnilSoni1999/spotify-dl#199]
**Q:**
HI

first of all thank you for this project, and really something indescribable you are the best. I'm writing to you because I've been experiencing this bug for a couple of days (I attach Screen) I don't want that I touched something and that's why it's wrong but basically I tried everything even formatting the pc and a new installation of windows... aaah I've already been talking to the creator of this spectacular tool. Is there a way to raise the music quality from 256kbps to 320kbps? Thank you very kind I can never thank you enough for this small but very powerful application.

P.S. I am attaching the error it gives me, you will surely be able to advise me...
Thanks in advance.
<img width="1440" alt="Screenshot 2023-05-25 alle 22 18 11" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/43850b10-1284-44f7-9d0d-503b98d60496">

**Comment by Starlord-199** [comment]
i finished downloading to see what it said at the end as you can see it tells me there is an error but i don't know how to fix it... it downloaded 68/100 please help.

<img width="1440" alt="Screenshot 2023-05-25 alle 22 43 48" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/ac7236ce-c5a1-42ce-848f-ce8b67eabc2a">
<img width="1440" alt="Screenshot 2023-05-25 alle 22 43 29" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/4b3532f1-03ab-43e6-8d87-5fa8511bca25">

**Comment by Giovancruz** [comment]
Same error here

**Comment by phyzical** [comment]
@Starlord-199 thanks i was able to repro with this track https://open.spotify.com/track/7ro0hRteUMfnOioTFI5TG1?si=19e868b33af34de0

![image](https://github.com/SwapnilSoni1999/spotify-dl/assets/5182053/6881d6ae-6158-41b9-a0c8-db5ca7711a6a)

im not sure whats causing it but its specific files/videos as others work fine so ill do a deeper debug later today

**Comment by Starlord-199** [comment]
thanks for the quick response yes I'm actually not the only one with this error. Thanks, I await news

**Comment by passandscore** [comment]
I had the same issue but was able to resolve it.

### **Error:**

>

ℹ Starting download of list 1/1
ℹ Downloading: Billie Jean Michael Jackson
ℹ Total Items: 1
ℹ 1/1
Artist: Michael Jackson
Album: Thriller
Item: Billie Jean
ℹ searching youtube with keywords "Thriller - Billie Jean"
⠇ Trying youtube link (https://youtube.com/watch?v=Zi_XLOBDo_Y) 1...evalmachine.<anonymous>:8
/,()[/,-71,//};Vla(ncode);
^

SyntaxError: Invalid regular expression: missing /
    at new Script (node:vm:100:7)
    at Object.exports.decipherFormats (/Users/jasonschwarz/spotify-dl/node_modules/ytdl-core/lib/sig.js:116:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Promise.all (index 0)
    at async exports.getInfo (/Users/jasonschwarz/spotify-dl/node_modules/ytdl-core/lib/info.js:401:17)
    

### **Solution:**
`npm install ytdl-core@latest`

**Comment by Starlord-199** [comment]
I tried to apply your solution by downloading the packages but unfortunately it still gives me the error as you can see from the screen

<img width="1440" alt="Screenshot 2023-05-26 alle 04 25 25" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/fee02bdd-48b1-402f-ba0b-2392b6ad2544">

**Comment by Giovancruz** [comment]
Also, besides this error, I'm facing this another one here many times:
`Error: EBUSY: resource busy or locked, rename 'C:\[...].ffmetadata.mp3' -> 'C:\[...].mp3'`

I'm not sure if this is relevant, but here's some infos:
```
Win: 11
Node: 14.21.3
NPM: 6.14.18
Spotifydl: 1.1.0
```

**Comment by phyzical** [comment]
@Starlord-199 do you mind giving it another try? i actually cant reproduce the issue anymore maybe it was a youtube api side issue?

**Comment by Starlord-199** [comment]
hi, yes, I've tried it now with three playlists and it seems to go very well... thanks for the work you've done, you've been very kind...

Now I have another question would it be possible to download from 256kbps to 320kbps?

**Comment by phyzical** [comment]
i'm afraid we already request the highest quality that the api provides as far as im aware https://github.com/fent/node-ytdl-core/blob/master/typings/index.d.ts#L36

**Comment by Starlord-199** [comment]
Yes, because I download by creating this string (spotifydl link playlist --output D:\Spotify) I don't know if I have to add any other rules... but if you tell me that it's okay and nothing can be done, that's fine already.

**Comment by Starlord-199** [comment]
Yes, because I download by creating this string (spotifydl link playlist --output D:\Spotify) I don't know if I have to add any other rules... but if you tell me that it's okay and nothing can be done, that's fine already.

**Comment by SwapnilSoni1999** [comment]
Please check on latest version and let me know
