### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'id')

### ISSUE THREAD

**Issue by pedroresende** [SwapnilSoni1999/spotify-dl#201]
**Describe the bug**

```js
> spotify-dl@1.1.2 start
> ./cli.js https://open.spotify.com/album/3EfF0Ull4AIq98w5Em5XMa

ℹ Starting processing of album (https://open.spotify.com/album/3EfF0Ull4AIq98w5Em5XMa)
ℹ Generating new access token
ℹ extracting 34 tracks
ℹ extracting track set 1/2
ℹ extracting track set 2/2
TypeError: Cannot read properties of null (reading 'id')
    at file:///Users/pedroresende/Projects/spotify-dl/lib/api.js:210:36
    at Array.find (<anonymous>)
    at parseTrack (file:///Users/pedroresende/Projects/spotify-dl/lib/api.js:209:40)
    at file:///Users/pedroresende/Projects/spotify-dl/lib/api.js:204:39
    at Array.map (<anonymous>)
    at extractTracks (file:///Users/pedroresende/Projects/spotify-dl/lib/api.js:204:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async extractAlbum (file:///Users/pedroresende/Projects/spotify-dl/lib/api.js:302:5)
    at async getAlbum (file:///Users/pedroresende/Projects/spotify-dl/util/get-songdata.js:12:10)
    at async run (file:///Users/pedroresende/Projects/spotify-dl/util/runner.js:167:22)
```

**To Reproduce**
1. run `npm run start https://open.spotify.com/album/3EfF0Ull4AIq98w5Em5XMa`

**Expected behavior**
To extract correctly the musics

**Desktop (please complete the following information):**
 - OS: MacOS 13.4

**Additional context**
Node version 18.16.0

**Comment by SwapnilSoni1999** [comment]
you supposed to use `spotifydl` command.

**Comment by pedroresende** [comment]
![image](https://github.com/SwapnilSoni1999/spotify-dl/assets/951377/58c295b8-d82b-418c-bd81-03b9110c0085)

😉

**Comment by pedroresende** [comment]
@SwapnilSoni1999 using the `spotifydl` command 

![image](https://github.com/SwapnilSoni1999/spotify-dl/assets/951377/ae81d15b-5a1b-4995-81bf-bc7adb0ad61c)

**Comment by phyzical** [comment]
@pedroresende sorry must have missed this one 
![image](https://github.com/SwapnilSoni1999/spotify-dl/assets/5182053/ccaf0763-974a-40c2-9178-46f76d0a5c57)


can confirm i can atleast replicate it, ill have a deeper look later today

**Comment by pedroresende** [comment]
> @pedroresende sorry must have missed this one ![image](https://user-images.githubusercontent.com/5182053/250697882-ccaf0763-974a-40c2-9178-46f76d0a5c57.png)
> 
> can confirm i can atleast replicate it, ill have a deeper look later today
> 
> (its a bug related to the latest wave of changes around adding more audio info to the files i.e bpm, subtitles)

You have here a "potential" fix https://github.com/SwapnilSoni1999/spotify-dl/pull/202
