### ISSUE TITLE
Download Path

### ISSUE THREAD

**Issue by PsychoGemini04** [SwapnilSoni1999/spotify-dl#207]
Hello, thanks for the spotifydl its working awesome, but it would be nice if there is an option to change the location where to download songs and if there is, please let me know the command and thanks !

**Comment by phyzical** [comment]
https://github.com/SwapnilSoni1999/spotify-dl#options

see -o

**Comment by PsychoGemini04** [comment]
thanks! but how to use the command because i i tried spotifydl -o (path) and its didnt work

**Comment by PsychoGemini04** [comment]
oh i didnt notice that, thanks !
