### ISSUE TITLE
no longer lets me download in any way

### ISSUE THREAD

**Issue by Starlord-199** [SwapnilSoni1999/spotify-dl#210]
Hi I'm here to report a bug that this amazing system of yours has been giving me for days, unfortunately it doesn't let me download music anymore, sometimes it downloads and it's fine other unfortunately it crashes and doesn't let me download anything anymore... giving me the following errors... I attach screenshot. is it possible to figure out how to fix it?

<img width="1440" alt="Screenshot 2023-08-30 alle 15 03 33" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/0e427ff4-e6b2-4ddd-b73a-36308257ad3d">
<img width="1440" alt="Screenshot 2023-09-05 alle 18 27 43" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/de6e745a-95e2-42a3-90a7-571b404b8f35">
<img width="1440" alt="Screenshot 2023-09-05 alle 19 01 33" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/db6fb9b1-74c7-4b5f-b610-dccc5f27c9b1">

**Comment by phyzical** [comment]
looks like generic timeouts could be anything,

are you running multiple at once? if so could just be your being rate limited?

**Comment by Starlord-199** [comment]
Yes I tried to do several sessions at the same time so I opened 5 windows at the same time I didn't know there was a limit, but now it's been two weeks if it was limited shouldn't it go back up? If not, how do I get it back up?

**Comment by phyzical** [comment]
it could be that your being limited by spotify or youtube.

It all depends on how they know its you, if its ip based restarting your router might change your public ip and get you out of the bad books

If you provide a user+pass you could try creating a throw away account and using that for auth and see if it starts working again.

**Comment by Starlord-199** [comment]
Unfortunately, I can't get a stable download even after restarting the modem, and trying a VPN doesn't even work, it always gives me the same error and repeats until it switches to the other tracks and so on.
 
<img width="1440" alt="Screenshot 2023-09-10 alle 03 37 29" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/31c285c8-b5ff-4d5a-a6cb-79d2adda4a74">

**Comment by Kenya-West** [comment]
Same here, same error as shown in message above

**Comment by phyzical** [comment]
no worries looks to be an issue with the package https://github.com/fent/node-ytdl-core/pull/1217

sorry @Starlord-199 was too busy to actually verify the issue

looks like pinning it to 4.10.0 seems to make it happy until the upstream package fix is merged.

![image](https://github.com/SwapnilSoni1999/spotify-dl/assets/5182053/250aee20-0c85-49af-b5e5-9b560c514f58)

**Comment by Starlord-199** [comment]
Thank you very much no it was not urgent thank you really for what you did this is the best music download program ever created you are kindest... Thanks again for your work ....
