### ISSUE TITLE
Error: ENOENT: no such file or directory

### ISSUE THREAD

**Issue by Starlord-199** [SwapnilSoni1999/spotify-dl#214]
Hi when I try to download with any link it gives me this error before it didn't give me this error could you tell me what is the problem and how can I solve it? is it for dear a bug?

Thank you for your reply
<img width="1440" alt="Screenshot 2023-10-01 alle 15 44 34" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/eaa650cd-0fb7-40af-8518-2bf10d4aa073">

**Comment by Kortuss** [comment]
i have the same issue when i try to download big playlist (more than 20 songs)

**Comment by Starlord-199** [comment]
hi yes but to me regardless I have is from 20 to or from 80 I can't understand why it doesn't let me download anymore... it always gives me this error I'm trying them all...

<img width="1440" alt="Screenshot 2023-10-02 alle 01 10 38" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/134628143/e763093b-2dba-4ec7-809a-111f568f0ddd">
