### ISSUE TITLE
Spotify API error for playlist >1400 tracks

### ISSUE THREAD

**Issue by lonzoweb** [SwapnilSoni1999/spotify-dl#216]
ℹ Generating new access token
ℹ extracting 1410 tracks
ℹ Got a spotify api error (WebapiError: [object Object])
Timing out for 5 minutes x 1

Is there a limit ?

**Comment by phyzical** [comment]
no is it a private playlist? or a playlist containing podcasts/episodes?

**Comment by lonzoweb** [comment]
> no is it a private playlist? or a playlist containing podcasts/episodes?

Don't think it has podcasts/episodes but I recently changed it to public from private

**Comment by phyzical** [comment]
try another playlist/album/song url just rule out your playlist first
