### ISSUE TITLE
403 during download

### ISSUE THREAD

**Issue by erobin27** [SwapnilSoni1999/spotify-dl#217]
**Describe the bug**
I was able to download songs fine and then the very same songs I was just downloading started throwing 403 errors. I tried to login with --l and grant permissions still same error. I then did the headless login, same error.

**To Reproduce**
1. Download song
2. Repeat? 

The song should just download as normal

**Screenshots**
<img width="921" alt="image" src="https://github.com/SwapnilSoni1999/spotify-dl/assets/47159753/dc384623-3c23-46ee-b3c0-63667fe198c8">

**Desktop (please complete the following information):**
 - OS: Mac OS [Apple Chip]
 - Browser: Chrome
 - Version: 119.0.6045.159

**Additional context**
It may be worth mentioning that the callback redirect after login is to an empty localhost page.

**Comment by erobin27** [comment]
I just tried again and it worked?...

**Comment by erobin27** [comment]
It seems to happen after I use the Spotify-dl a lot. I'm running it in a for loop to download 10 individual songs so I think I am getting this error after running it about 3 times or so.

403 goes away after a break so I'm thinking I am being throttled maybe but idk why it would return 403 for that.

**Comment by phyzical** [comment]
@erobin27 it could be how the app was designed, as each invocation would probably get a new token. 

i cant 100% remember but i think we made it allow multiple urls at once, so could try providing all urls to the cli.

https://github.com/SwapnilSoni1999/spotify-dl/blob/master/lib/setup.js#L310

The code does suggest we support multiple input urls
