### ISSUE TITLE
podcast downloading error.

### ISSUE THREAD

**Issue by arvindmn01** [SwapnilSoni1999/spotify-dl#220]
Hi,
I tried to download spotify episode using the below command.
```
spotifydl https://open.spotify.com/episode/6ptE0E81rdhzsEWeZTmkAp --l
```
I am able to download it, but the audio length is only 5 minutes, whereas the actual podcast length is 32 minutes. Additionally, while downloading, the total MB it was downloading was 60 mb, but after it finished, the audio size is only 10MB.

**Comment by arvindmn01** [comment]
@phyzical 
yes it is actually downloading this video [youtube video](https://www.youtube.com/watch?v=JxCfbLyIaCE) from youtube instead of actual podcast from spotify.
Is it possible to download the original podcast?

**Comment by phyzical** [comment]
thio package can only use youtube.

`searching youtube with keywords "${searchTerms}"` 

this log should show what its using to try and best guess

If you find there is a better search term that lines up on youtube in general better then its up to configure `--search-format` 

i think be default it just searches youtube for `SHOW - EPISODE_NAME`

**Comment by arvindmn01** [comment]
@phyzical Thanks for the detailed response. 
However, my requirements are completely different. If I can find the podcast on YouTube, then I can easily download it. My specific need is to download podcasts that are not on YouTube but only on Spotify.

**Comment by phyzical** [comment]
@arvindmn01 no worries, checkout this https://github.com/jsavargas/zspotify 

Good luck 👍
