### ISSUE TITLE
Filename format and additional info

### ISSUE THREAD

**Issue by IcyFoxe** [SwapnilSoni1999/spotify-dl#229]
Is there an option to specify filename in custom manner, for example: `{artistName} - {songName}`?
From the documentation it doesn't seem that it's currently possible. Would it be possible to add such feature?

By default it sorts files into folders which are named by artist name, but if we use `--output-only`, it will create list of songs without artist names. It would take a lot of time to rename all this files individually by hand.

**Comment by phyzical** [comment]
sorry about the delay, request is reasonable. will look at implementing this week

**Comment by phyzical** [comment]
@IcyFoxe this is now implemented in master example usage is as follows `--of "{albumName}___{artistName}___{itemName}"`, but more in depth description can be found on the readme/help

**Comment by IcyFoxe** [comment]
Thank you very much, I'll give it a try today!

**Comment by IcyFoxe** [comment]
@phyzical After trying it out, I'm getting this error, maybe you'll know what's causing it:
```
Error: ENOENT: no such file or directory, mkdir
    at Object.mkdirSync (node:fs:1414:3)
    at downloadList (file:///C:/Users/Icy/AppData/Roaming/npm/node_modules/spotify-dl/util/runner.js:79:10)
    at run (file:///C:/Users/Icy/AppData/Roaming/npm/node_modules/spotify-dl/util/runner.js:270:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
I installed the package from this github page, like you told me.

**Comment by phyzical** [comment]
@IcyFoxe what was the exact command ran so i can try and replicate.

Also was there any more error trace?

**Comment by IcyFoxe** [comment]
I installed the package from your repo master branch using npm (I even tried downloading it locally).
It doesn't matter what command I use, even the very basic one `spotifydl some-url`, it throws this error. That's the whole error message after it queues the first song from the playlist. Feel free to try yourself https://open.spotify.com/playlist/0K15yDsoxPAS21wY21rfp9?si=b0c7dab71fdb49a0 (later I'll delete this url).

**Comment by phyzical** [comment]
hmmm @IcyFoxe sorry what i mean by error is the full trace of logs that is output for example when i run it with your provided playlist

```
./cli.js "https://open.spotify.com/playlist/0K15yDsoxPAS21wY21rfp9?si=b0c7dab71fdb49a0 "   
ℹ Starting processing of playlist (https://open.spotify.com/playlist/0K15yDsoxPAS21wY21rfp9)
ℹ Generating new access token
ℹ extracting 99 tracks
ℹ Starting download of list 1/1
ℹ Downloading: My Playlist - IcyTheWhite
ℹ Total Items: 99
ℹ 1/99
Artist: Binary Haze Interactive
Album: ENDER LILIES: Quietus of the Knights Original Soundtrack
Item: Lily
ℹ searching youtube with keywords "ENDER LILIES: Quietus of the Knights Original Soundtrack - Lily"
⠹ Trying youtube link (https://youtube.com/watch?v=PTKl17TXqyo) 1...WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest".
✔ Download completed (/Users/phyzical/Sites/spotify-dl/Binary Haze Interactive/ENDER LILIES Quietus of the Knights Original Soundtrack/Lily.mp3).
✔ Metadata Merged!
```

**Comment by phyzical** [comment]
/facepalm i have found the issue i exploded on "/" but windows it will come in as "\" i will have a fix in master shortly

**Comment by IcyFoxe** [comment]
Ah, the classic slashes.. Alright, glad you managed to find it.

**Comment by phyzical** [comment]
@IcyFoxe fix is now in master lmk if there are any more issues 👍
