### ISSUE TITLE
downloads the wrong song

### ISSUE THREAD

**Issue by zmatical** [SwapnilSoni1999/spotify-dl#244]
i have tried to download a song using the spotify link with either of these examples: 

spotifydl "https://open.spotify.com/track/2a8FNTijWDiS6HjmBtGLT6?si=e91612716e574596" --output C:\Users\User\Downloads\Music

or this 

node cli.js "https://open.spotify.com/track/2a8FNTijWDiS6HjmBtGLT6?si=e91612716e574596" --oft "flac" --output C:\Users\User\Downloads\Music

and it downloads the wrong song, this is not the first time btw, but did i miss something? what's the fix?

**Comment by phyzical** [comment]
```
The ability to find a video is dependent on the fact it is hosted on youtube, and even then there is a chance it is still incorrectly matched
```

If you look in the output it should say how its searching youtube for the songs. It just gets the closest match first

**Comment by zmatical** [comment]
what's a a way to make it more accurate?
