### ISSUE TITLE
If I want to download a public playlist, I get an error

### ISSUE THREAD

**Issue by mpskyman** [SwapnilSoni1999/spotify-dl#245]
If I want to download one of my public playlist that is linked on my profile I get the error: "Got a spotify api error (WebapiError: [object Object])"

Command that I used
- spotifydl.cmd https://open.spotify.com/playlist/4vmPM7qhsJvZVFZz10sHP9?si=c4c83aaac2ed4319 --oo

maybe it is some sort of rate limiting?

**Comment by phyzical** [comment]
is it a private playlist?

**Comment by mpskyman** [comment]
No, it is Public, you can check the link to see for yourself.

**Comment by phyzical** [comment]
hmm did you get this part way through or straight away?

**Comment by mpskyman** [comment]
Straight away.
ℹ Starting processing of playlist (https://open.spotify.com/playlist/5QHkN2f196ivsEgD0zsUGZ)
ℹ Generating new access token
ℹ extracting 3930 tracks
ℹ Got a spotify api error (WebapiError: [object Object])
Timing out for 5 minutes x 1

**Comment by mpskyman** [comment]
I don't know what I just did, but after retrying it a few times on different computers and all the time with the npm package, and the GitHub release it just worked. I also tried it on Linux (WSL Debian and Arch on my Laptop) and Windows 11, and it just started working.

**Comment by phyzical** [comment]
@mpskyman it could be rate limit related, it could also have been the github source version generated a token that the npm version wasnt able to. but now the npm version can reuse 

Ahwell good to hear it worked
