### ISSUE TITLE
Output format jpg is not available

### ISSUE THREAD

**Issue by PaulmagCookies** [SwapnilSoni1999/spotify-dl#246]
**Describe the bug**
When downloading a file normally using the command `spotifydl --oo https://open.spotify.com/track/59FTa368w1dyNqvkJv54VR?si=04570b9213854516` I get the error
`i Album Thumbnail corrupt attempting again
i Album Thumbnail corrupt for second time fallback to generic image
Error: Output format jpg is not available`
But the weird thing is that this only happens if I install spotify-dl with npm. If I clone the github repo and use `node cli.js --oo https://open.spotify.com/track/59FTa368w1dyNqvkJv54VR?si=04570b9213854516`

**To Reproduce**
1. `npm i -g spotify-dl`
2. `spotifydl --oo https://open.spotify.com/track/59FTa368w1dyNqvkJv54VR?si=04570b9213854516`

**Expected behavior**
ffmpeg should accept the image normally like the cloned version.

**Screenshots**
![grafik](https://github.com/SwapnilSoni1999/spotify-dl/assets/78360417/7b94ce0c-0ed4-4f78-baa0-f6eb79f529b5)

**Desktop**
It was tested on a windows 10 PC another two windows 11 PCs and on Linux Mint.

**Additional context**
I already tried to console.log the image url and it actually gave a jpeg. I don't know why this doesn't work.

**Comment by phyzical** [comment]
the version of npm is getting a bit out of date, i dont have permission to make releases on npm.

i assume thats why. if the owner doesnt get back to me ill make a secondary package to start automated builds to.

ill let you know when thats ready for a retest

**Comment by isuvorov** [comment]
The same

**Comment by DerZyklop** [comment]
Nice! I can confirm: 

With `npm install -g spotify-dl`, it does **not** work. 

With manual installation, it works. From the readme:

```
git clone https://github.com/SwapnilSoni1999/spotify-dl
cd spotify-dl
npm install
npm link
```

**Comment by phyzical** [comment]
have worked around it by publishing to github instead please use this going forward`npm install -g https://github.com/swapnilsoni1999/spotify-dl`
