### ISSUE TITLE
Input stream error: Status code: 403

### ISSUE THREAD

**Issue by vaskitchu** [SwapnilSoni1999/spotify-dl#248]
When downloading my playlist, it gives me the following two errors: "Output format m4a is not available" and  "Input stream error: Status code: 403". I've already downloaded using this tool without any problems before, I'm testing with a playlist that's proven to work; no music or playlist works; I've tested with several.

**To Reproduce**
1. spotifydl --dr --oo --o "C:\Users\Utilizador\spotify-dl\musicas" --oft "mp3" "https://open.spotify.com/playlist/1zYYTsU4gQW2SS7ruIzBDj?si=zsC16hjCQ4iFeI8uuHIfgw&pi=e-uXrHvI3uTPSw"

**Expected behavior**
It is expected for the files to be downloaded.

**Screenshots**
![image](https://github.com/user-attachments/assets/e22596e1-47f7-4d1a-9549-288522b2c6b7)

Desktop :
 - OS: Windows 10
 - Using CMD
 - Version 1.0.8

I've tested reinstalling and updating ffmpeg, and spotify-dl, I've also tried without any effect the following commands: "youtube-dl --rm-cache-dir" and "pip install yt-dlp --upgrade".

**Comment by Hx-Regex** [comment]
I am encountering similar issues with multiple Spotify download libraries. Could it be possible that Spotify or YouTube has implemented some sort of blocker?

**Comment by phyzical** [comment]
Yeah i can confirm, its something youtube has changed. the library we rely on hasnt got an update in about a year,

ive hacked together a fix using `https://www.npmjs.com/package/youtube-dl-exec` instead. 

But ill need to take some more time to workout how to add back all the functionailty.

**Comment by phyzical** [comment]
Ive just merged a quick fix into master , moves us over to a fork that resolves the issue.

NOTE: this pushes the minimum node version up to node 18

**Comment by vaskitchu** [comment]
I'm sorry but it still isn't working for me with the same error  :/
My case is very specific, so I might be using some functionalities that have not been added.
I can wait for the full updated version if you are still going to do it.
