### ISSUE TITLE
Error: Output format jpg is not available when downloading a track

### ISSUE THREAD

**Issue by Hx-Regex** [SwapnilSoni1999/spotify-dl#253]
**Description**:
I encountered an issue when using `spotify-dl` to download a track from Spotify. The process completes the download successfully but fails when attempting to handle the album thumbnail. The error message indicates that the output format `jpg` is not available.

**Steps to Reproduce**:
1. Run the following command:
   ```sh
   spotifydl https://open.spotify.com/track/3CIyK1V4JEJkg02E4EJnDl?si=65c18639a6a94689


**ERROR**
```
Error: Output format jpg is not available
    at C:\Users\hexga\AppData\Roaming\npm\node_modules\@swapnilsoni1999\spotify-dl\node_modules\fluent-ffmpeg\lib\capabilities.js:589:21
    at fn (C:\Users\hexga\AppData\Roaming\npm\node_modules\@swapnilsoni1999\spotify-dl\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\hexga\AppData\Roaming\npm\node_modules\@swapnilsoni1999\spotify-dl\node_modules\async\lib\async.js:498:34)
    at process.processImmediate (node:internal/timers:478:21)
```



```
└─# spotifydl https://open.spotify.com/track/3CIyK1V4JEJkg02E4EJnDl?si=65c18639a6a94689
ℹ Starting processing of song (https://open.spotify.com/track/3CIyK1V4JEJkg02E4EJnDl)
ℹ extracting track set 1/1
ℹ Generating new access token

========Update Available========
Use npm install -g spotify-dl
to update the package.
================================

ℹ Starting download of list 1/1
ℹ Downloading: Enemy (with JID) - from the series Arcane League of Legends Imagine Dragons
ℹ Total Items: 1
ℹ 1/1
Artist: Imagine Dragons
Album: Mercury - Acts 1 & 2
Item: Enemy (with JID) - from the series Arcane League of Legends
ℹ searching youtube with keywords "Mercury - Acts 1 & 2 - Enemy (with JID) - from the series Arcane League of Legends"
✔ Download completed (C:\Users\hewga\Desktop\Work\projet\Imagine Dragons\Mercury - Acts 1  2\Enemy (with JID) - from the series Arcane League of Legends.mp3).
ℹ Album Thumbnail corrupt attempting again
ℹ Album Thumbnail corrupt for second time fallback to generic image
Error: Output format jpg is not available
    at C:\Users\hexga\AppData\Roaming\npm\node_modules\@swapnilsoni1999\spotify-dl\node_modules\fluent-ffmpeg\lib\capabilities.js:589:21
    at fn (C:\Users\hexga\AppData\Roaming\npm\node_modules\@swapnilsoni1999\spotify-dl\node_modules\async\lib\async.js:582:34)
    at Immediate.<anonymous> (C:\Users\hexga\AppData\Roaming\npm\node_modules\@swapnilsoni1999\spotify-dl\node_modules\async\lib\async.js:498:34)
    at process.processImmediate (node:internal/timers:478:21)

```

**Comment by phyzical** [comment]
See new install in the readme not from npm anymore.
