### ISSUE TITLE
No album art

### ISSUE THREAD

**Issue by ImDarkShadow** [SwapnilSoni1999/spotify-dl#27]
Songs downloading without album art

**Comment by SwapnilSoni1999** [comment]
Thing is it shows in vlc 
Have to figure it out though.

**Comment by SwapnilSoni1999** [comment]
Fixed! will be publishing soon!
![image](https://user-images.githubusercontent.com/25403317/78305693-359c4c80-755f-11ea-8e3a-5b846497a62d.png)
