### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by inglesuniversal** [SwapnilSoni1999/spotify-dl#28]
can this script be accessible on a website once installed on a LAMP server?

another question:

how can I configure the output so I get:

ARTIST - TRACK.mp3 (instead of the opposite)

best regards

**Comment by inglesuniversal** [comment]
Any update on my feature request?

**Comment by SwapnilSoni1999** [comment]
Actually I was working on it and recently, I messed up with my code so had to redo it. You have to wait little longer else you can reference following lines to edit 

https://github.com/SwapnilSoni1999/spotify-dl/blob/master/cli.js#L87
https://github.com/SwapnilSoni1999/spotify-dl/blob/master/cli.js#L107
https://github.com/SwapnilSoni1999/spotify-dl/blob/master/cli.js#L120

here you can edit last argument to change your desired output

**Comment by inglesuniversal** [comment]
I think I messed up the code .... :(

> 
⠙ Downloading...events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: ffmpeg was killed with signal SIGABRT
    at ChildProcess.<anonymous> (/usr/local/lib/node_modules/spotify-dl/node_modules/fluent-ffmpeg/lib/processor.js:180:22)
    at ChildProcess.emit (events.js:315:20)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
>

**Comment by SwapnilSoni1999** [comment]
seems like ffmpeg error and its not full log though

**Comment by SaiTeja69** [comment]
Remember to define --pkg-config-flags="--static"
