### ISSUE TITLE
Eternal loading

### ISSUE THREAD

**Issue by KapelS** [SwapnilSoni1999/spotify-dl#30]
![Снимок экрана от 2020-05-02 17-52-11](https://user-images.githubusercontent.com/63398526/80867629-d9336680-8c9d-11ea-8d85-9a2fa33a20fb.png)
Not loading, eternal loading
Some songs do not want to download

**Comment by SwapnilSoni1999** [comment]
Can you please try with vpn and inform. 
Thanks.
