### ISSUE TITLE
FFmpeg Windows 64 executable not supported

### ISSUE THREAD

**Issue by eegli** [SwapnilSoni1999/spotify-dl#31]
If you are on Windows 10 64-bit and add the 64-bit version of FFmpeg to your path, it will not work. With the 32-bit executable, everything is fine.

Might be worth adding this to the readme at least. https://ffmpeg.zeranoe.com/builds/

**Comment by SwapnilSoni1999** [comment]
When I made it was working.. Strange though, also I don't have windows machine but I'll surely look in this issue asap. Thanks.
