### ISSUE TITLE
Can only download 10 songs then get error on 11th.

### ISSUE THREAD

**Issue by Dialpuri** [SwapnilSoni1999/spotify-dl#33]
![image](https://user-images.githubusercontent.com/44945647/83272301-e1aa8e80-a1c2-11ea-942c-61fc00a61b1a.png)
Here is the error I get

**Comment by SwapnilSoni1999** [comment]
not sure though what's happening. I'm also not aware when and why this happens. But you can still continue downloading from where you left it will automatically resume it

**Comment by the-tiny-semicolon** [comment]
I got this too, i think it is api limit that a user can download at a time

**Comment by Mahdios** [comment]
![image](https://user-images.githubusercontent.com/64026951/84671532-c90ed800-af27-11ea-8785-8995626e5d68.png)
Its stuck on the first song for me

**Comment by Dialpuri** [comment]
was working before for me but now I get the same error as Mahdi

**Comment by SwapnilSoni1999** [comment]
im still not aware why this error is occurring 
But i will try to find asap.

**Comment by KallelGaNewk** [comment]
same problem for me

![unknown](https://user-images.githubusercontent.com/61438367/86519869-6d908580-be15-11ea-890b-87b3af6702ce.png)

**Comment by SwapnilSoni1999** [comment]
I have fixed this in 1fad4b0108a8b8acc03e122c9eec319606cd9ea1

**Comment by Dialpuri** [comment]
When was the problem?

**Comment by Dialpuri** [comment]
What*

**Comment by SwapnilSoni1999** [comment]
@Dialpuri 
sometimes the `yt-search` module returns with only with `/watch?id=xxx` and sometimes full url so i placed a condition to check if that contains full url or not if it contains then join domain string else dont.

**Comment by SwapnilSoni1999** [comment]
your'e welcome <3
