### ISSUE TITLE
Download shows episodes

### ISSUE THREAD

**Issue by BrOrlandi** [SwapnilSoni1999/spotify-dl#34]
Is there a way to support downloading shows episodes?
I would like to download some podcast episodes.

Let me know if it's possible and if yes, what does need to change in the code?

**Comment by BrOrlandi** [comment]
I take a deeper look at the code. You use youtube to download the songs. So, it will not work to download shows episodes as I guess it's maybe not available on youtube or anywhere else.

**Comment by SwapnilSoni1999** [comment]
It is using youtube to download songs and also mentioned in README.md 
If that podcast is available then it will get downloaded.
