### ISSUE TITLE
The tool fails to create a dir with the playlist's name

### ISSUE THREAD

**Issue by Mahdios** [SwapnilSoni1999/spotify-dl#35]
**Expected behavior**:  Create a directory to save songs into.
**Current behavior**: Fails to create the directory.
**Platform**:  Win64
**Reason**:  The playlist's name contains illegal chars (like **:**) witch cannot be set in a directory's name.
**Fix**:  Implement a check or a regular expression to find and replace illegal chars
i would be happy to adjust it and open a pr  if you allow me to :)

**Comment by SwapnilSoni1999** [comment]
thanks alot <3 will implement this

**Comment by SwapnilSoni1999** [comment]
can you share the song url so I can test.

**Comment by Mahdios** [comment]
Any song or playlist with a smiley face (**: )** ) will do

**Comment by SwapnilSoni1999** [comment]
i have checked the `:` symbol gets sliced in a utility function
strange though

**Comment by Mahdios** [comment]
hmmm, let me retry with a test playlist. I'll keep u updated.

**Comment by Mahdios** [comment]
strange, seems to be working very well now
