### ISSUE TITLE
m4a audio instead of mp3

### ISSUE THREAD

**Issue by nagualcode** [SwapnilSoni1999/spotify-dl#40]
Is it possible to let the audio format in m4a?
m4a is the youtube native audio data, so there is no need to do a lossy converstion to mp3 (unless user can only play mp3 format).

**Comment by SwapnilSoni1999** [comment]
Well ytdl-core converts it to mp3 by default with bestaudio but still you can pass your own custom arguments though

**Comment by nagualcode** [comment]
pass m4a argument is spotify-dl ? When file/line should I edit?

**Comment by nagualcode** [comment]
ytdl-core prefers m4a, maybe spotify-dl could prefer it too?
https://github.com/fent/node-ytdl-core/blob/master/lib/util.js#L6

Anyway, thanks.
