### ISSUE TITLE
Get rid of FFMG

### ISSUE THREAD

**Issue by prabaprakash** [SwapnilSoni1999/spotify-dl#41]
Hi, @SwapnilSoni1999 I have created scripts for saavn, pluralsight, hotstar etc  I don't know why need ffmg tools in the first place. will you get rid of it?

**Comment by SwapnilSoni1999** [comment]
> Hi, @SwapnilSoni1999 I have created scripts for saavn, pluralsight, hotstar etc I don't know why need ffmg tools in the first place. will you get rid of it?

I am using it for merging metadata and piping it with ytdl-core
