### ISSUE TITLE
Specifying where to download doesnt work after new update.

### ISSUE THREAD

**Issue by Saniee** [SwapnilSoni1999/spotify-dl#45]
So there was the new update. I downloaded it and tried to download a song. I go to the folder i specified. Nothing. I check the folder where the npm module is installed and they are there. They also got a rather wierd name. I specified D:\Music, the song name would have DMusic infront of the file. Please ik that if I go to the D:\Music folder it will install there but im too lazy. Also sending a screen. [Here is the screenshot!](https://bit.ly/2QBhsMc)

**Comment by SwapnilSoni1999** [comment]
its fixed on pr #48
