### ISSUE TITLE
Tried to download a long album, it failed.

### ISSUE THREAD

**Issue by Saniee** [SwapnilSoni1999/spotify-dl#46]
[Here is the error screenshot.](https://bit.ly/2QynOLZ)

`× Something went wrong!
TypeError: Cannot read property 'forEach' of undefined
    at C:\Users\Samuel Škula\AppData\Roaming\npm\node_modules\spotify-dl\lib\api.js:94:44
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Spotifye.extrAlbum (C:\Users\Samuel Škula\AppData\Roaming\npm\node_modules\spotify-dl\util\get-songdata.js:43:23)
    at async C:\Users\Samuel Škula\AppData\Roaming\npm\node_modules\spotify-dl\cli.js:141:22
`

**Comment by SwapnilSoni1999** [comment]
You can always continue with same command in same directory it will resume. 
infact I wasn't aware why it throws error so I had to create a resume download feature.
