### ISSUE TITLE
[request] publish package to npm registry?

### ISSUE THREAD

**Issue by pavanjadhaw** [SwapnilSoni1999/spotify-dl#5]
Publishing spotifydl to npm registry will make it easier for users to install spotifydl seemlessly without hassle using single command
```
npm install -g spotifydl
```

You can also publish it as scoped package if spotifydl name is already taken
```
npm install -g @swapnilsoni/spotifydl
```

**Comment by SwapnilSoni1999** [comment]
yes, I have plans for that currently I'm having exams so not working right now, will surely publish

**Comment by SwapnilSoni1999** [comment]
;_; Probably need `__dirname` to `process.cwd()` to make it global command

**Comment by pavanjadhaw** [comment]
Actually it will work without any changes, if you see the demo gif [here](https://github.com/pavanjadhaw/spotifydl) you would notice it is working without running node cli.js

It has installed executable which can execute using spotifydl command.

**Comment by pavanjadhaw** [comment]
[Docs](https://docs.npmjs.com/files/package.json#bin) for reference and we have already added it.
So now all you need to do is publish package to [npmjs.com](https://www.npmjs.com/)
[Here](https://docs.npmjs.com/packages-and-modules/contributing-packages-to-the-registry) is official documentation on publishing your packages to npm

**Comment by SwapnilSoni1999** [comment]
I know but problem is its saving where the cli.json is... need to make it more dynamic like youtube-dl to use over any directory

**Comment by pavanjadhaw** [comment]
Oh I forgot about that, the latest commit on my [fork](https://github.com/pavanjadhaw/spotifydl/commit/9eae70dcd9295b1a3e079cc6dbc5844899a03ccd) will fix it.
Cherrypick it and you are good to go.

**Comment by SwapnilSoni1999** [comment]
Done with publishing on npm <3 

You can install with 
`npm install -g spotify-dl`
or
`sudo npm install -g spotify-dl`

**Comment by pavanjadhaw** [comment]
Awesome
