### ISSUE TITLE
Tried to download a song, the song is not on youtube and it downloaded the first result, which is a 4.5 hour compilation

### ISSUE THREAD

**Issue by Pawiiiiii** [SwapnilSoni1999/spotify-dl#51]
Tried to download https://open.spotify.com/track/5FAm2NCjU38DdARBhdwEzT
What was downloaded: https://www.youtube.com/watch?v=fbDwaUej4aE
I tried searching for the song on youtube, but I couldn't find it, so I guess that's why, but still, there should be a limit/confirmation for song length, maybe error if it's not found, since it was stuck at 0MB out of 0MB until it finished, and the result file is over 500MB.

**Comment by SwapnilSoni1999** [comment]
It is downloading from youtube. So it might happen that sometimes song is not available on youtube so according to search results the wrong url is fetched and as a result some wrong song/music gets downloaded.

**Comment by miraclx** [comment]
I'd recommend you implement some sort of result classifier that would filter through results, excluding bad matches and download the best option (if any).

[freyr-js] does this [See [here](https://github.com/miraclx/freyr-js/blob/9c11c60898f18d8405124b8ee27a8dac05a30624/src/services/youtube.js#L404-L465) for reference]

Or better still, search YouTube Music instead, then most of the result classification is done for you. You'd then just have to parse the results and sort for the preferred audio source.

Again, [freyr-js] does this [See [here](https://github.com/miraclx/freyr-js/blob/9c11c60898f18d8405124b8ee27a8dac05a30624/src/services/youtube.js#L275-L337) for reference]

[freyr-js]: https://github.com/miraclx/freyr-js

**Comment by miraclx** [comment]
If you're going with the second option, because there isn't any official API for YouTube Music, you'd have to scrape the website for data.

[freyr-js] does this [here](https://github.com/miraclx/freyr-js/blob/9c11c60898f18d8405124b8ee27a8dac05a30624/src/services/youtube.js#L106-L261)

[freyr-js]: https://github.com/miraclx/freyr-js

**Comment by theofficialgrand1** [comment]
> Tried to download https://open.spotify.com/track/5FAm2NCjU38DdARBhdwEzT
> What was downloaded: https://www.youtube.com/watch?v=fbDwaUej4aE
> I tried searching for the song on youtube, but I couldn't find it, so I guess that's why, but still, there should be a limit/confirmation for song length, maybe error if it's not found, since it was stuck at 0MB out of 0MB until it finished, and the result file is over 500MB.

Dude next time watch your terminal as it tells you how big the song file is.

**Comment by phyzical** [comment]
i will see if i can solve this as part of my refactor pr, i ran into this when it tried to dl a 1.4gb file by default, "just sitting there and watching" isnt really an option when you have a cron that auto runs downloads to get more songs automatically
