### ISSUE TITLE
Album Failing to download

### ISSUE THREAD

**Issue by Miles1701** [SwapnilSoni1999/spotify-dl#57]
![Screenshot_20201121-185056](https://user-images.githubusercontent.com/71639017/99875429-a5646200-2c2a-11eb-85e8-9ceb66086745.png)

Every album I try it failed for unknown reasons.

**Comment by SwapnilSoni1999** [comment]
Please check on [latest](https://github.com/SwapnilSoni1999/spotify-dl/releases/latest) release. 
If worked then please close issue.
Thanks.
