### ISSUE TITLE
Tag for v0.4.7 in the wrong place

### ISSUE THREAD

**Issue by DavidGriffith** [SwapnilSoni1999/spotify-dl#63]
I just did a pull and a fresh pull just to make sure.  The tags `v0.4.6` and `v0.4.7` both point to the same commit.  The commit after that bumps the version to `v0.4.7`, so the `v0.4.7` should probably be set there too.

**Comment by SwapnilSoni1999** [comment]
yes i got messed up with tags but not to worry next version will fix tags issue
