### ISSUE TITLE
[enhancement] Use "lyric" in the search query for Youtube

### ISSUE THREAD

**Issue by burhanuday** [SwapnilSoni1999/spotify-dl#65]
Searching Youtube for music will always land the official video as the top result
Official videos have blank audio for music videos which is not a part of the song itself
Searching for a lyric video instead will find a result which is not the official video

Example:
Billie Ellish - Therefore I Am lyrics

**Comment by burhanuday** [comment]
Shouldnt be difficult to implement. Point me to the file where the song metadata is fetched, and I'll open a PR for it

**Comment by burhanuday** [comment]
```
const result = await search(songName + ' lyrics');
```
I made this change in `get-link.js` and it seems to have fixed this problem
Let me know if i should open a PR

**Comment by SwapnilSoni1999** [comment]
Will add some extra arg for adding custom keywords eg. `spotifydl <url> --extra-search "lyric"`

**Comment by miraclx** [comment]
You might be able to get higher audio quality by classifying results from several queries (As suggested [here](https://github.com/SwapnilSoni1999/spotify-dl/issues/51#issuecomment-765050026))

[freyr-js] uses 4 by default when searching YouTube [ref](https://github.com/miraclx/freyr-js/blob/9c11c60898f18d8405124b8ee27a8dac05a30624/src/services/youtube.js#L417-L422)

- `- Official Audio`
- `- Audio`
- `- Lyrics`
- `- `

Then afterward, it classifies the results from each query, removing duplicates and sorting by relevance, duration, most views until the best track is selected.

Or better still, search YouTube Music instead (As suggested [here](https://github.com/SwapnilSoni1999/spotify-dl/issues/51#issuecomment-765050026))

[freyr-js]: https://github.com/miraclx/freyr-js

**Comment by SwapnilSoni1999** [comment]
Added feature in [v0.5.0](https://github.com/SwapnilSoni1999/spotify-dl/releases/tag/0.5.0)
