### ISSUE TITLE
Downloading not Working!

### ISSUE THREAD

**Issue by ProxyPing** [SwapnilSoni1999/spotify-dl#69]
https://upload.proxyping.de/putty_BRniKAhMeG.png

**Comment by miraclx** [comment]
Check out freyr-js...https://github.com/miraclx/freyr-js

**Comment by capriciousduck** [comment]
@ProxyPing Did you intsall ffmpeg?

**Comment by ProxyPing** [comment]
> @ProxyPing Did you intsall ffmpeg?

@capriciousduck yeah..

**Comment by capriciousduck** [comment]
@ProxyPing Going through the other issues, I've come to know that the script has problems downloading the songs from an "album", though it worked fine with playlists. One quick workaround is to add the album to a playlist and fetch it.

**Comment by SwapnilSoni1999** [comment]
working on same thing, same issue was mentioned on #64
