### ISSUE TITLE
[freyr-js]: Alternative supporting multiple services, many features and customization options

### ISSUE THREAD

**Issue by miraclx** [SwapnilSoni1999/spotify-dl#70]
Nice work on this; I've been working on something similar for the past year now

**freyr-js** https://github.com/miraclx/freyr-js
- supports multiple streaming services (Spotify, Apple Music, Deezer, and more to come)
- automatically embeds album art and song metadata
- exports M4A audio supported in iTunes
- has a myriad of options for customizing the experience (Alternate sources, preferred bitrate, etc...)
- and many more features

Do check it out

**Comment by SwapnilSoni1999** [comment]
Nice work but I dont think so this topic suited for an 'ISSUE'

**Comment by miraclx** [comment]
Yeah, sorry, I couldn't find a better place to put it.

Would an alternatives section in the README do?

I could add one in freyr too
