### ISSUE TITLE
Spotifydl doesnt work!

### ISSUE THREAD

**Issue by theofficialgrand1** [SwapnilSoni1999/spotify-dl#72]
For example when I input this command:
spotifydl https://open.spotify.com/track/16j29x0j2fDzuYBRwpTnla?si=W_F1ByeXQTmgwCV5ZkbL7Q

It comes back with:
zsh: no matches found: https://open.spotify.com/track/16j29x0j2fDzuYBRwpTnla?si=W_F1ByeXQTmgwCV5ZkbL7Q
Im using MacOS
Pls help thanks! Appreciate this project!

**Comment by SwapnilSoni1999** [comment]
install using `sudo npm install -g spotify-dl@latest`

**Comment by SnwMds** [comment]
Question marks are interpreted as a pattern in zsh shell.

Put your link inside quotes or escape the `?`:

```bash
$ spotifydl 'https://open.spotify.com/track/16j29x0j2fDzuYBRwpTnla?si=W_F1ByeXQTmgwCV5ZkbL7Q'
```

or


```bash
$ spotifydl https://open.spotify.com/track/16j29x0j2fDzuYBRwpTnla\?si=W_F1ByeXQTmgwCV5ZkbL7Q
```

**Comment by theofficialgrand1** [comment]
> Question marks are interpreted as a pattern in zsh shell.
> 
> Put your link inside quotes:
> 
> ```shell
> $ spotifydl 'https://open.spotify.com/track/16j29x0j2fDzuYBRwpTnla?si=W_F1ByeXQTmgwCV5ZkbL7Q'
> ```
> 
> ...or escape the question mark:
> 
> ```shell
> $ spotifydl https://open.spotify.com/track/16j29x0j2fDzuYBRwpTnla\?si=W_F1ByeXQTmgwCV5ZkbL7Q
> ```

Thanks! You guys are great help!
