### ISSUE TITLE
Download Problem

### ISSUE THREAD

**Issue by theofficialgrand1** [SwapnilSoni1999/spotify-dl#75]
So during downloading a playlist, songs seem to disappear from the folder. For example I have 200 songs in one playlist, although the command line says everything is full downloaded, my folder info only shows 92 items. Why is this so, is this a bug? Hope you can address the issue.

This is the playlist that doesn't work (https://open.spotify.com/playlist/6J08oqfmAdKRrRlkIMR5LK?si=yjU4g-uUTcWKypvQ1iymXQ), Its quite long though.

**Comment by chiumax** [comment]
It seems that spotify dl limits play list lengths to 100

**Comment by SwapnilSoni1999** [comment]
> It seems that spotify dl limits play list lengths to 100

Well actually not it checks total length and loops through all of them

**Comment by theofficialgrand1** [comment]
> > It seems that spotify dl limits play list lengths to 100
> 
> Well actually not it checks total length and loops through all of them

What do you mean by that so it looks through the songs but doesn't download all?

**Comment by SwapnilSoni1999** [comment]
> > > It seems that spotify dl limits play list lengths to 100
> > 
> > 
> > Well actually not it checks total length and loops through all of them
> 
> What do you mean by that so it looks through the songs but doesn't download all?

it does. it downloads all of them

**Comment by HenriHawk42** [comment]
> > It seems that spotify dl limits play list lengths to 100
> 
> Well actually not it checks total length and loops through all of them

Can you elaborate? I only saw about 101 songs in the music directory I set, after attempting to download a 600ish library. Is there any fix for this?

**Comment by phyzical** [comment]
@battlezone do you mind trying my pr? https://github.com/SwapnilSoni1999/spotify-dl/pull/84 i have made a bunch of refactors and i am wondering if i have fixed this

**Comment by phyzical** [comment]
nvm i can confirm this is till a bug... still looking into it

**Comment by phyzical** [comment]
this is now fixed on  https://github.com/SwapnilSoni1999/spotify-dl/pull/84 feel free to try it out before its merged to help confirm it has been fixed 👍
