### ISSUE TITLE
Discord.js support need

### ISSUE THREAD

**Issue by L0SER8228** [SwapnilSoni1999/spotify-dl#76]
I want to use this on discord bot made with javascript and discord.js. But i can't find any way to do that . How can I do that ?
Please help me

**Comment by chiumax** [comment]
I don't think bots can attach files to messages. You would need something like a user account and interact with Discord's API from there. However, it's against Discord's TOS.

**Comment by SwapnilSoni1999** [comment]
Sorry if that's against discord's TOS then I can't help with that
