### ISSUE TITLE
[feature] download a song using YT link directly from CLI

### ISSUE THREAD

**Issue by burhanuday** [SwapnilSoni1999/spotify-dl#80]
This sounds like its outside the scope of this package but hear me out.
We already have all the necessary stuff to be able to do this and i found a song not on spotify but available on YT
I could download and use yt-dl separately but having this option here feels convenient

**Comment by SwapnilSoni1999** [comment]
well we have [youtube-dl](yt-dl.org) for that though. 
But still I'll try to add `--yt` option to pass youtube links 
Setting this as a low priority issue

**Comment by phyzical** [comment]
This would be fairly simple to implement, 
i dont think it will even need a --yt tag rather we just make another case to the cli for when it contains youtube to just skip all spotify parsing ill lump it in my my pr 👍
