### ISSUE TITLE
not possible to download episodes (as opposed to tracks)?

### ISSUE THREAD

**Issue by stuart-little** [SwapnilSoni1999/spotify-dl#81]
I am trying this:

```
spotifydl https://open.spotify.com/episode/7bi51Qn1vNJlsF67C4GYb7
```
The result:
```
✖ Something went wrong!
Error: Invalid URL type
    at /usr/lib/node_modules/spotify-dl/cli.js:193:17
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```
Downloading from `https://open.spotify.com/track/<blah>` URLs works fine.

**Comment by stuart-little** [comment]
Actually, I don't think this will help me anyway..

I think it should be possible to extract info from an `/episode/` URL by supplementing your [api.js](https://github.com/SwapnilSoni1999/spotify-dl/blob/8852fd0be4e78822003168bac0f37aecfd7748e3/lib/api.js) with a `getEpisode` function using the [relevant Spotify api](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-an-episode).

However: I thought you had some magical way of extracting `mp3`s from the track data. Since the downloads are through youtube instead, this won't help with, say, Spotify-only podcasts that are not on youtube.

Or am I missing anything?

**Comment by SwapnilSoni1999** [comment]
> Actually, I don't think this will help me anyway..
> 
> I think it should be possible to extract info from an `/episode/` URL by supplementing your [api.js](https://github.com/SwapnilSoni1999/spotify-dl/blob/8852fd0be4e78822003168bac0f37aecfd7748e3/lib/api.js) with a `getEpisode` function using the [relevant Spotify api](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-an-episode).
> 
> However: I thought you had some magical way of extracting `mp3`s from the track data. Since the downloads are through youtube instead, this won't help with, say, Spotify-only podcasts that are not on youtube.
> 
> Or am I missing anything?

Yes exactly @stuart-little Youtube will have different content based on the episode title from spotify. So it will be useless to implement downloading episodes feature.
