### ISSUE TITLE
WARNING: ytdl-core is out of date! Update with "npm install ytdl-core@latest"

### ISSUE THREAD

**Issue by mevsme** [SwapnilSoni1999/spotify-dl#86]
Where should I call this? I tried many folders: `c:\program files\nodejs`,  `%AppData%\npm\node_modules`, as global command

It throws warnings and errors and then still show message that ytdl is out of date. How do I fix this?

**Comment by phyzical** [comment]
that is just a warning but will still work fine, im sure this package will be updated at some point by the maintainer

imo this is closable
