### ISSUE TITLE
If the song is deleted (no artis and title in the playlis, just empty entry) the script will abort downloading of a playlist

### ISSUE THREAD

**Issue by mevsme** [SwapnilSoni1999/spotify-dl#87]
![image](https://user-images.githubusercontent.com/1394030/117045877-b3a9c480-ad18-11eb-84e8-27be6cd8f6fe.png)
Here is an example

**Comment by phyzical** [comment]
could  you please link a (preferably) smallish playlist/album/song link to help replicate this
