### ISSUE TITLE
spotifydl can not handle a bat file with list of downloads

### ISSUE THREAD

**Issue by mevsme** [SwapnilSoni1999/spotify-dl#88]
![image](https://user-images.githubusercontent.com/1394030/117046160-03888b80-ad19-11eb-8c05-6344b446b4c2.png)

This kind of list would work with youtube-dl and ffmpeg but somehow doesn't work with spotify-dl 😞

**Comment by phyzical** [comment]
bit more information might help :)

for example is there any errors?

**Comment by raprocks** [comment]
As a Workaround you can make a playlist of those songs, make it public and then download it
