### ISSUE TITLE
Add support for providing users login details

### ISSUE THREAD

**Issue by phyzical** [SwapnilSoni1999/spotify-dl#90]
This will allow support for things like "download all saved songs" or "downlaod all saved albums" or "download all saved playlists"

i will start this when my current pr is merged

**Comment by SwapnilSoni1999** [comment]
Alright <3 Seems exciting :) thank you so much for your contribution.

**Comment by phyzical** [comment]
This isnt as simple as i first thought ;( due to user and pass not being an accepted auth process for 3rd parties these days (which makes sense). 

But i think i may have an idea run a simple webserver to have the spotify api redirect back to with the user signed token.

Now i think.. this will work but it means this will only work in TTY environments so doesn't solve i.e docker usage...

ill keep thinking and see if i can come up with something... puppeteer + chromium webdriver may do an entirely headless approach maybe?

**Comment by SwapnilSoni1999** [comment]
Well my token is public then I guess we should not do this because it may expose some information to others. Maybe I'm wrong I haven't researched much on the API

**Comment by phyzical** [comment]
there was an approach that worked by only using the client ID and not the secret. but webservers alone cannot pipe in a # segment which is how the token is returned from spotify in this approach ;( (ill give it a few more tries)

i was able to generate a user signed token with the webserver approach still playing around with it.

So i understand your concern What information are you worried about? personal information. if so we could just create a random new spotify developer  account and create the app on that so its not tied to you specifically if you like?

**Comment by SwapnilSoni1999** [comment]
I mean if someone could be able to access other user's data which are authorized with our clientid and secret (or the developer app)

**Comment by phyzical** [comment]
hmm i dont think this will be an issue, like if someone does use the id and secret they would still need to pipe the user to spotify and ask for their consent (which requires a login) before being able to do anything with their data. though i may be overlooking something
