### ISSUE TITLE
Add Test suite

### ISSUE THREAD

**Issue by phyzical** [SwapnilSoni1999/spotify-dl#99]
we probably should do this will remove some need to manually test peoples code

Would also look at triggering this in github action on a specific command/ condition to reduce free minutes usage

**Comment by SwapnilSoni1999** [comment]
well i dont get it can you please elaborate

**Comment by phyzical** [comment]
so, we write a test suite to test each parts of the code.

It is then triggered on pr commits to verify the PR does not break anything, this allows for further confidence in the code being committed is correct to both the reviewer and submitter

**Comment by SwapnilSoni1999** [comment]
Yeah good idea

**Comment by phyzical** [comment]
not yet bot
